// Stone Age tech tree data.
// Eras span ~3.3 Mya (Oldowan) to ~3000 BCE (Neolithic / Chalcolithic transition).
// Each tech: id, name, era, category, year (approx earliest evidence), prereqs[], desc

const ERAS = [
  { id: "lower-paleo",  name: "Lower Paleolithic",  range: "3.3 Mya – 300 kya" },
  { id: "middle-paleo", name: "Middle Paleolithic", range: "300 – 50 kya" },
  { id: "upper-paleo",  name: "Upper Paleolithic",  range: "50 – 12 kya" },
  { id: "mesolithic",   name: "Mesolithic",         range: "12 – 9 kya" },
  { id: "neolithic",    name: "Neolithic",          range: "9 – 5 kya" },
];

const CATEGORIES = {
  tools:       { name: "Tools & Materials",   color: "#7dd3fc" },
  subsistence: { name: "Subsistence",         color: "#86efac" },
  shelter:     { name: "Shelter & Mobility",  color: "#fcd34d" },
  social:      { name: "Social & Cognitive",  color: "#f0abfc" },
  weapons:     { name: "Weapons & Hunting",   color: "#fda4af" },
};

const TECHS = [
  // ─── Lower Paleolithic ─────────────────────────────────────────
  { id: "oldowan", name: "Oldowan Stone Tools", era: "lower-paleo", category: "tools",
    year: "~3.3 Mya", prereqs: [],
    desc: "Simple chipped stone flakes and choppers. The first identifiable stone tool industry, made by Australopithecus and early Homo." },
  { id: "scavenging", name: "Organized Scavenging", era: "lower-paleo", category: "subsistence",
    year: "~2.6 Mya", prereqs: ["oldowan"],
    desc: "Using sharp flakes to butcher carcasses left by predators. First reliable access to high-calorie meat and marrow." },
  { id: "fire-use", name: "Use of Fire", era: "lower-paleo", category: "tools",
    year: "~1.5 Mya", prereqs: [],
    desc: "Tending naturally occurring fire for warmth, light, and predator deterrence. Possibly used by Homo erectus." },
  { id: "acheulean", name: "Acheulean Hand Axes", era: "lower-paleo", category: "tools",
    year: "~1.76 Mya", prereqs: ["oldowan"],
    desc: "Bifacially worked teardrop-shaped hand axes. Symmetrical, multipurpose, and produced for over a million years." },
  { id: "windbreaks", name: "Windbreaks & Camps", era: "lower-paleo", category: "shelter",
    year: "~1.8 Mya", prereqs: [],
    desc: "Temporary brush windbreaks around hearths. The first identifiable home-bases." },
  { id: "wooden-spear", name: "Wooden Thrusting Spear", era: "lower-paleo", category: "weapons",
    year: "~400 kya", prereqs: ["acheulean"],
    desc: "Fire-hardened wooden spears (Schöningen). First evidence of cooperative big-game hunting." },
  { id: "fire-making", name: "Fire-Making", era: "lower-paleo", category: "tools",
    year: "~400 kya", prereqs: ["fire-use"],
    desc: "Producing fire on demand by friction or percussion. Independent of natural sources." },
  { id: "cooking", name: "Cooking", era: "lower-paleo", category: "subsistence",
    year: "~400 kya", prereqs: ["fire-making", "scavenging"],
    desc: "Heat-processing food. Unlocks calories, kills pathogens, and is hypothesized to drive brain expansion." },

  // ─── Middle Paleolithic ────────────────────────────────────────
  { id: "levallois", name: "Levallois Technique", era: "middle-paleo", category: "tools",
    year: "~300 kya", prereqs: ["acheulean"],
    desc: "Prepared-core knapping that yields predictable flake shapes. A major leap in cognitive planning." },
  { id: "hafting", name: "Hafting", era: "middle-paleo", category: "tools",
    year: "~200 kya", prereqs: ["levallois"],
    desc: "Binding stone points to wooden shafts with sinew, pitch, or birch tar. Enables composite tools." },
  { id: "hide-clothing", name: "Hide Clothing", era: "middle-paleo", category: "shelter",
    year: "~170 kya", prereqs: ["acheulean"],
    desc: "Scraped and worked animal hides used as garments. Critical for cold-climate expansion." },
  { id: "pigments", name: "Pigments & Body Paint", era: "middle-paleo", category: "social",
    year: "~160 kya", prereqs: [],
    desc: "Ochre processing for symbolic decoration. Earliest evidence of abstract thought." },
  { id: "composite-spear", name: "Composite Spear", era: "middle-paleo", category: "weapons",
    year: "~150 kya", prereqs: ["hafting", "wooden-spear"],
    desc: "Stone-tipped throwing and thrusting spears. Increased lethality and standoff distance." },
  { id: "burial", name: "Deliberate Burial", era: "middle-paleo", category: "social",
    year: "~120 kya", prereqs: ["pigments"],
    desc: "Intentional interment of the dead, sometimes with grave goods. Suggests ritual and possibly belief in afterlife." },
  { id: "shellfishing", name: "Shellfish Gathering", era: "middle-paleo", category: "subsistence",
    year: "~165 kya", prereqs: ["cooking"],
    desc: "Coastal foraging for mollusks. A reliable, high-protein food source supporting population growth." },

  // ─── Upper Paleolithic ─────────────────────────────────────────
  { id: "blade-tech", name: "Blade Technology", era: "upper-paleo", category: "tools",
    year: "~50 kya", prereqs: ["levallois"],
    desc: "Long, narrow flakes struck from prismatic cores. Yields more cutting edge per kilogram of stone." },
  { id: "bone-tools", name: "Bone & Antler Tools", era: "upper-paleo", category: "tools",
    year: "~45 kya", prereqs: ["blade-tech"],
    desc: "Awls, points, and shafts shaped from bone, antler, and ivory. Opens new material classes." },
  { id: "atlatl", name: "Spear-Thrower (Atlatl)", era: "upper-paleo", category: "weapons",
    year: "~30 kya", prereqs: ["composite-spear"],
    desc: "Lever that doubles dart range and velocity. Effective on large game from a safer distance." },
  { id: "needles", name: "Eyed Needles", era: "upper-paleo", category: "tools",
    year: "~40 kya", prereqs: ["bone-tools", "hide-clothing"],
    desc: "Bone needles with drilled eyes enable fitted, layered clothing. Essential for survival in glacial Eurasia." },
  { id: "cave-art", name: "Cave Painting", era: "upper-paleo", category: "social",
    year: "~40 kya", prereqs: ["pigments"],
    desc: "Figurative animal paintings (Chauvet, Lascaux, Sulawesi). Sophisticated representational art." },
  { id: "figurines", name: "Figurines & Sculpture", era: "upper-paleo", category: "social",
    year: "~35 kya", prereqs: ["bone-tools", "pigments"],
    desc: "Carved Venus figurines and animal sculptures in ivory and stone. Portable symbolic objects." },
  { id: "flute", name: "Bone Flute", era: "upper-paleo", category: "social",
    year: "~40 kya", prereqs: ["bone-tools"],
    desc: "The earliest known musical instruments, carved from bird bones and mammoth ivory." },
  { id: "harpoon", name: "Barbed Harpoon", era: "upper-paleo", category: "weapons",
    year: "~25 kya", prereqs: ["bone-tools"],
    desc: "Detachable barbed points for fishing and aquatic hunting. Prevents prey from escaping the line." },
  { id: "trade-networks", name: "Long-Distance Trade", era: "upper-paleo", category: "social",
    year: "~30 kya", prereqs: ["figurines"],
    desc: "Movement of obsidian, shell, and ochre across hundreds of kilometers. Implies durable social ties." },
  { id: "rafts", name: "Rafts & Dugouts", era: "upper-paleo", category: "shelter",
    year: "~50 kya", prereqs: [],
    desc: "Watercraft enabling the colonization of Sahul (Australia) by ~50 kya. Earliest open-sea voyaging." },
  { id: "microliths", name: "Microliths", era: "upper-paleo", category: "tools",
    year: "~35 kya", prereqs: ["blade-tech"],
    desc: "Tiny standardized blades set into composite tools. Modular, replaceable, and economical with stone." },

  // ─── Mesolithic ────────────────────────────────────────────────
  { id: "bow-arrow", name: "Bow and Arrow", era: "mesolithic", category: "weapons",
    year: "~12 kya (widespread)", prereqs: ["atlatl", "microliths"],
    desc: "Stored elastic energy weapon. Quiet, accurate, fast to reload — transforms hunting and warfare." },
  { id: "dog", name: "Dog Domestication", era: "mesolithic", category: "subsistence",
    year: "~15 kya", prereqs: ["bone-tools"],
    desc: "Wolves bred into hunting and camp companions. The first domesticated species." },
  { id: "fishing-net", name: "Fishing Nets", era: "mesolithic", category: "subsistence",
    year: "~10 kya", prereqs: ["harpoon"],
    desc: "Knotted plant-fiber nets and traps. Mass capture of fish supports semi-sedentary life." },
  { id: "basketry", name: "Basketry & Cordage", era: "mesolithic", category: "tools",
    year: "~12 kya", prereqs: [],
    desc: "Plaited containers and twisted fiber rope. Critical for storage, transport, and rigging." },
  { id: "canoe", name: "Dugout Canoe", era: "mesolithic", category: "shelter",
    year: "~10 kya", prereqs: ["rafts"],
    desc: "Hollowed log canoes (Pesse). Reliable inland and coastal travel and trade." },
  { id: "semi-sedentism", name: "Semi-Sedentary Camps", era: "mesolithic", category: "shelter",
    year: "~12 kya", prereqs: ["fishing-net", "shellfishing"],
    desc: "Year-round or seasonal base camps near abundant resources. A bridge to true village life." },

  // ─── Neolithic ─────────────────────────────────────────────────
  { id: "plant-cultivation", name: "Plant Cultivation", era: "neolithic", category: "subsistence",
    year: "~11 kya", prereqs: ["basketry", "semi-sedentism"],
    desc: "Deliberate sowing and tending of wild cereals. The opening move of the Agricultural Revolution." },
  { id: "animal-domestication", name: "Animal Domestication", era: "neolithic", category: "subsistence",
    year: "~10.5 kya", prereqs: ["dog"],
    desc: "Sheep, goat, pig, and cattle herding. Provides meat, milk, hides, and draft power on demand." },
  { id: "polished-stone", name: "Polished Stone Axes", era: "neolithic", category: "tools",
    year: "~10 kya", prereqs: ["microliths"],
    desc: "Ground and polished stone heads — durable enough to fell large trees and clear forest for fields." },
  { id: "pottery", name: "Pottery", era: "neolithic", category: "tools",
    year: "~10 kya", prereqs: ["cooking", "basketry"],
    desc: "Fired clay vessels for cooking, fermentation, and storage. Independently invented many times." },
  { id: "village", name: "Permanent Villages", era: "neolithic", category: "shelter",
    year: "~10 kya", prereqs: ["semi-sedentism", "plant-cultivation"],
    desc: "Mudbrick and timber settlements (Jericho, Çatalhöyük). Hundreds to thousands of residents." },
  { id: "weaving", name: "Loom Weaving", era: "neolithic", category: "tools",
    year: "~9 kya", prereqs: ["basketry", "animal-domestication"],
    desc: "Warp-and-weft textiles from flax and wool. Replaces hides for most everyday garments." },
  { id: "megaliths", name: "Megalithic Monuments", era: "neolithic", category: "social",
    year: "~11 kya", prereqs: ["village", "trade-networks"],
    desc: "Göbekli Tepe and later stone circles. Communal ritual architecture predating agriculture in some cases." },
  { id: "granary", name: "Granaries & Storage", era: "neolithic", category: "subsistence",
    year: "~9 kya", prereqs: ["plant-cultivation", "pottery"],
    desc: "Dedicated structures for surplus grain. Underwrites population growth and incipient inequality." },
];

window.TECH_TREE = { ERAS, CATEGORIES, TECHS };
