// Human History Tech Tree — full timeline.
// Eras span the Lower Paleolithic (~3.3 Mya) through the Information Age (present).
// Each tech: { id, name, era, category, year (approx earliest evidence), prereqs[], desc }

const ERAS = [
  { id: "lower-paleo",   name: "Lower Paleolithic",  range: "3.3 Mya – 300 kya" },
  { id: "middle-paleo",  name: "Middle Paleolithic", range: "300 – 50 kya" },
  { id: "upper-paleo",   name: "Upper Paleolithic",  range: "50 – 12 kya" },
  { id: "mesolithic",    name: "Mesolithic",         range: "12 – 9 kya" },
  { id: "neolithic",     name: "Neolithic",          range: "9 – 5 kya" },
  { id: "bronze",        name: "Bronze Age",         range: "3300 – 1200 BCE" },
  { id: "classical",     name: "Classical Antiquity",range: "1200 BCE – 500 CE" },
  { id: "medieval",      name: "Medieval",           range: "500 – 1450 CE" },
  { id: "renaissance",   name: "Renaissance",        range: "1450 – 1650" },
  { id: "enlightenment", name: "Enlightenment",      range: "1650 – 1800" },
  { id: "industrial",    name: "Industrial",         range: "1800 – 1914" },
  { id: "modern",        name: "Modern",             range: "1914 – 1970" },
  { id: "information",   name: "Information",        range: "1970 – present" },
];

const CATEGORIES = {
  tools:         { name: "Tools & Materials",       color: "#7dd3fc" },
  subsistence:   { name: "Subsistence & Agriculture", color: "#86efac" },
  shelter:       { name: "Shelter & Architecture",  color: "#fcd34d" },
  social:        { name: "Social & Cultural",       color: "#f0abfc" },
  weapons:       { name: "Weapons & Warfare",       color: "#fda4af" },
  knowledge:     { name: "Knowledge & Science",     color: "#a78bfa" },
  energy:        { name: "Energy & Power",          color: "#fb923c" },
  transport:     { name: "Transport & Mobility",    color: "#22d3ee" },
  medicine:      { name: "Medicine & Health",       color: "#34d399" },
  communication: { name: "Communication & Media",   color: "#facc15" },
  economy:       { name: "Economy & Governance",    color: "#c084fc" },
};

const TECHS = [
  // ─── Lower Paleolithic ─────────────────────────────────────────
  { id: "bipedal-gait", name: "Bipedal Locomotion", era: "lower-paleo", category: "subsistence",
    year: "~6 Mya", prereqs: [],
    desc: "Habitual upright walking, freeing the hands for tool use and load-carrying. The defining hominin trait." },
  { id: "wooden-club", name: "Wooden Club", era: "lower-paleo", category: "weapons",
    year: "~3 Mya", prereqs: [],
    desc: "Hand-held wooden bludgeons. The simplest weapon — leaves no archaeological trace but inferred from primate analogues." },
  { id: "gestural-communication", name: "Gestural Communication", era: "lower-paleo", category: "social",
    year: "~3 Mya", prereqs: [],
    desc: "Coordinated signaling with hands, posture, and vocal calls. Precursor to spoken language." },
  { id: "oldowan", name: "Oldowan Stone Tools", era: "lower-paleo", category: "tools",
    year: "~3.3 Mya", prereqs: [],
    desc: "Simple chipped stone flakes and choppers. The first identifiable stone tool industry, made by Australopithecus and early Homo." },
  { id: "scavenging", name: "Organized Scavenging", era: "lower-paleo", category: "subsistence",
    year: "~2.6 Mya", prereqs: ["oldowan"],
    desc: "Using sharp flakes to butcher carcasses left by predators. First reliable access to high-calorie meat and marrow." },
  { id: "persistence-hunting", name: "Persistence Hunting", era: "lower-paleo", category: "weapons",
    year: "~2 Mya", prereqs: ["bipedal-gait"],
    desc: "Endurance running to exhaust prey under midday heat. Exploits human thermoregulation and stamina." },
  { id: "fire-use", name: "Use of Fire", era: "lower-paleo", category: "tools",
    year: "~1.5 Mya", prereqs: [],
    desc: "Tending naturally occurring fire for warmth, light, and predator deterrence. Possibly used by Homo erectus." },
  { id: "acheulean", name: "Acheulean Hand Axes", era: "lower-paleo", category: "tools",
    year: "~1.76 Mya", prereqs: ["oldowan"],
    desc: "Bifacially worked teardrop-shaped hand axes. Symmetrical, multipurpose, and produced for over a million years." },
  { id: "windbreaks", name: "Windbreaks & Camps", era: "lower-paleo", category: "shelter",
    year: "~1.8 Mya", prereqs: [],
    desc: "Temporary brush windbreaks around hearths. The first identifiable home-bases." },
  { id: "wooden-spear", name: "Wooden Thrusting Spear", era: "lower-paleo", category: "weapons",
    year: "~400 kya", prereqs: ["acheulean"],
    desc: "Fire-hardened wooden spears (Schöningen). First evidence of cooperative big-game hunting." },
  { id: "fire-making", name: "Fire-Making", era: "lower-paleo", category: "tools",
    year: "~400 kya", prereqs: ["fire-use"],
    desc: "Producing fire on demand by friction or percussion. Independent of natural sources." },
  { id: "cooking", name: "Cooking", era: "lower-paleo", category: "subsistence",
    year: "~400 kya", prereqs: ["fire-making", "scavenging"],
    desc: "Heat-processing food. Unlocks calories, kills pathogens, and is hypothesized to drive brain expansion." },

  // ─── Middle Paleolithic ────────────────────────────────────────
  { id: "digging-stick", name: "Digging Stick", era: "middle-paleo", category: "tools",
    year: "~300 kya", prereqs: ["oldowan"],
    desc: "Sharpened sticks for unearthing tubers, roots, and small game. The most important wooden tool of foragers." },
  { id: "levallois", name: "Levallois Technique", era: "middle-paleo", category: "tools",
    year: "~300 kya", prereqs: ["acheulean"],
    desc: "Prepared-core knapping that yields predictable flake shapes. A major leap in cognitive planning." },
  { id: "hafting", name: "Hafting", era: "middle-paleo", category: "tools",
    year: "~200 kya", prereqs: ["levallois"],
    desc: "Binding stone points to wooden shafts with sinew, pitch, or birch tar. Enables composite tools." },
  { id: "birch-tar", name: "Birch-Bark Tar", era: "middle-paleo", category: "tools",
    year: "~200 kya", prereqs: ["fire-making", "levallois"],
    desc: "Heat-distilled adhesive from birch bark. The world's first synthetic material, used to glue stone to wood." },
  { id: "hide-clothing", name: "Hide Clothing", era: "middle-paleo", category: "shelter",
    year: "~170 kya", prereqs: ["acheulean"],
    desc: "Scraped and worked animal hides used as garments. Critical for cold-climate expansion." },
  { id: "shellfishing", name: "Shellfish Gathering", era: "middle-paleo", category: "subsistence",
    year: "~165 kya", prereqs: ["cooking"],
    desc: "Coastal foraging for mollusks. A reliable, high-protein food source supporting population growth." },
  { id: "pigments", name: "Pigments & Body Paint", era: "middle-paleo", category: "social",
    year: "~160 kya", prereqs: [],
    desc: "Ochre processing for symbolic decoration. Earliest evidence of abstract thought." },
  { id: "composite-spear", name: "Composite Spear", era: "middle-paleo", category: "weapons",
    year: "~150 kya", prereqs: ["hafting", "wooden-spear"],
    desc: "Stone-tipped throwing and thrusting spears. Increased lethality and standoff distance." },
  { id: "shell-beads", name: "Shell Beads", era: "middle-paleo", category: "social",
    year: "~140 kya", prereqs: ["pigments", "shellfishing"],
    desc: "Pierced shell ornaments strung as necklaces. The earliest known personal jewelry and identity markers." },
  { id: "water-flask", name: "Water Containers", era: "middle-paleo", category: "tools",
    year: "~120 kya", prereqs: ["shellfishing"],
    desc: "Ostrich-eggshell flasks and gourds. Portable water enables travel through arid landscapes." },
  { id: "burial", name: "Deliberate Burial", era: "middle-paleo", category: "social",
    year: "~120 kya", prereqs: ["pigments"],
    desc: "Intentional interment of the dead, sometimes with grave goods. Suggests ritual and possibly belief in afterlife." },
  { id: "proto-language", name: "Proto-Language", era: "middle-paleo", category: "social",
    year: "~100 kya", prereqs: ["gestural-communication", "cooking"],
    desc: "Spoken communication beyond simple calls. Hyoid bone anatomy and FOXP2 gene point to articulate speech." },

  // ─── Upper Paleolithic ─────────────────────────────────────────
  { id: "rafts", name: "Rafts & Dugouts", era: "upper-paleo", category: "transport",
    year: "~50 kya", prereqs: [],
    desc: "Watercraft enabling the colonization of Sahul (Australia) by ~50 kya. Earliest open-sea voyaging." },
  { id: "blade-tech", name: "Blade Technology", era: "upper-paleo", category: "tools",
    year: "~50 kya", prereqs: ["levallois"],
    desc: "Long, narrow flakes struck from prismatic cores. Yields more cutting edge per kilogram of stone." },
  { id: "bone-tools", name: "Bone & Antler Tools", era: "upper-paleo", category: "tools",
    year: "~45 kya", prereqs: ["blade-tech"],
    desc: "Awls, points, and shafts shaped from bone, antler, and ivory. Opens new material classes." },
  { id: "needles", name: "Eyed Needles", era: "upper-paleo", category: "tools",
    year: "~40 kya", prereqs: ["bone-tools", "hide-clothing"],
    desc: "Bone needles with drilled eyes enable fitted, layered clothing. Essential for survival in glacial Eurasia." },
  { id: "cave-art", name: "Cave Painting", era: "upper-paleo", category: "social",
    year: "~40 kya", prereqs: ["pigments"],
    desc: "Figurative animal paintings (Chauvet, Lascaux, Sulawesi). Sophisticated representational art." },
  { id: "flute", name: "Bone Flute", era: "upper-paleo", category: "social",
    year: "~40 kya", prereqs: ["bone-tools"],
    desc: "The earliest known musical instruments, carved from bird bones and mammoth ivory." },
  { id: "bow-drill", name: "Bow Drill", era: "upper-paleo", category: "tools",
    year: "~40 kya", prereqs: ["fire-making", "bone-tools"],
    desc: "Friction fire-starter using a bow to spin a spindle. Mechanical advantage applied to fire-making." },
  { id: "tally-bones", name: "Tally Marks", era: "upper-paleo", category: "knowledge",
    year: "~40 kya", prereqs: ["bone-tools"],
    desc: "Notched bones (Lebombo, Ishango) recording counts. The earliest known mathematical artifacts." },
  { id: "oil-lamp", name: "Oil Lamp", era: "upper-paleo", category: "tools",
    year: "~40 kya", prereqs: ["fire-making", "bone-tools"],
    desc: "Stone basins burning animal fat with moss wicks. Portable artificial light extends the working day." },
  { id: "spun-fiber", name: "Spun Fiber & Cordage", era: "upper-paleo", category: "tools",
    year: "~36 kya", prereqs: ["bone-tools"],
    desc: "Twisted plant-fiber rope (Dzudzuana). Enables nets, snares, hafting, and rigging." },
  { id: "figurines", name: "Figurines & Sculpture", era: "upper-paleo", category: "social",
    year: "~35 kya", prereqs: ["bone-tools", "pigments"],
    desc: "Carved Venus figurines and animal sculptures in ivory and stone. Portable symbolic objects." },
  { id: "microliths", name: "Microliths", era: "upper-paleo", category: "tools",
    year: "~35 kya", prereqs: ["blade-tech"],
    desc: "Tiny standardized blades set into composite tools. Modular, replaceable, and economical with stone." },
  { id: "shamanism", name: "Shamanism", era: "upper-paleo", category: "social",
    year: "~30 kya", prereqs: ["cave-art", "burial"],
    desc: "Ritual specialists mediating with spirit worlds through trance, costume, and music. The first religious profession." },
  { id: "trade-networks", name: "Long-Distance Trade", era: "upper-paleo", category: "economy",
    year: "~30 kya", prereqs: ["figurines"],
    desc: "Movement of obsidian, shell, and ochre across hundreds of kilometers. Implies durable social ties." },
  { id: "atlatl", name: "Spear-Thrower (Atlatl)", era: "upper-paleo", category: "weapons",
    year: "~30 kya", prereqs: ["composite-spear"],
    desc: "Lever that doubles dart range and velocity. Effective on large game from a safer distance." },
  { id: "lunar-tally", name: "Lunar Calendar", era: "upper-paleo", category: "knowledge",
    year: "~30 kya", prereqs: ["tally-bones"],
    desc: "Bone notations tracking moon phases. The first systematic timekeeping." },
  { id: "harpoon", name: "Barbed Harpoon", era: "upper-paleo", category: "weapons",
    year: "~25 kya", prereqs: ["bone-tools"],
    desc: "Detachable barbed points for fishing and aquatic hunting. Prevents prey from escaping the line." },

  // ─── Mesolithic ────────────────────────────────────────────────
  { id: "dog", name: "Dog Domestication", era: "mesolithic", category: "subsistence",
    year: "~15 kya", prereqs: ["bone-tools"],
    desc: "Wolves bred into hunting and camp companions. The first domesticated species." },
  { id: "ground-stone", name: "Ground Stone Tools", era: "mesolithic", category: "tools",
    year: "~13 kya", prereqs: ["microliths"],
    desc: "Pecked, ground, and polished stone heads. Slower to make but far more durable than chipped tools." },
  { id: "bow-arrow", name: "Bow and Arrow", era: "mesolithic", category: "weapons",
    year: "~12 kya", prereqs: ["atlatl", "microliths"],
    desc: "Stored elastic energy weapon. Quiet, accurate, fast to reload — transforms hunting and warfare." },
  { id: "spun-fiber-mat", name: "Mat Weaving", era: "mesolithic", category: "tools",
    year: "~12 kya", prereqs: ["spun-fiber"],
    desc: "Plaited grass and reed mats for floors, roofs, and sails. The simplest woven textile." },
  { id: "basketry", name: "Basketry", era: "mesolithic", category: "tools",
    year: "~12 kya", prereqs: ["spun-fiber"],
    desc: "Plaited containers and traps. Critical for storage, transport, and food processing." },
  { id: "semi-sedentism", name: "Semi-Sedentary Camps", era: "mesolithic", category: "shelter",
    year: "~12 kya", prereqs: ["shellfishing"],
    desc: "Year-round or seasonal base camps near abundant resources. A bridge to true village life." },
  { id: "mortar-pestle", name: "Mortar & Pestle", era: "mesolithic", category: "tools",
    year: "~12 kya", prereqs: ["ground-stone"],
    desc: "Stone vessels for grinding seeds, nuts, and pigments. Unlocks calorie-dense plant foods." },
  { id: "sickle-flint", name: "Flint Sickle", era: "mesolithic", category: "subsistence",
    year: "~12 kya", prereqs: ["microliths"],
    desc: "Curved hafted blades for harvesting wild cereals. Natufian sickles preceded farming itself." },
  { id: "fishing-net", name: "Fishing Nets", era: "mesolithic", category: "subsistence",
    year: "~10 kya", prereqs: ["harpoon", "spun-fiber"],
    desc: "Knotted plant-fiber nets and traps. Mass capture of fish supports semi-sedentary life." },
  { id: "fish-weir", name: "Fish Weirs", era: "mesolithic", category: "subsistence",
    year: "~10 kya", prereqs: ["basketry"],
    desc: "Stone or wattle barriers funneling fish into traps. Industrial-scale fishing without nets." },
  { id: "canoe", name: "Dugout Canoe", era: "mesolithic", category: "transport",
    year: "~10 kya", prereqs: ["rafts"],
    desc: "Hollowed log canoes (Pesse). Reliable inland and coastal travel and trade." },
  { id: "snowshoe-ski", name: "Snowshoes & Skis", era: "mesolithic", category: "transport",
    year: "~10 kya", prereqs: ["basketry", "hide-clothing"],
    desc: "Wood-and-sinew snow gear. Opens boreal and tundra zones to sustained winter travel." },

  // ─── Neolithic ─────────────────────────────────────────────────
  { id: "plant-cultivation", name: "Plant Cultivation", era: "neolithic", category: "subsistence",
    year: "~11 kya", prereqs: ["basketry", "semi-sedentism", "sickle-flint"],
    desc: "Deliberate sowing and tending of wild cereals. The opening move of the Agricultural Revolution." },
  { id: "animal-domestication", name: "Animal Domestication", era: "neolithic", category: "subsistence",
    year: "~10.5 kya", prereqs: ["dog"],
    desc: "Sheep, goat, pig, and cattle herding. Provides meat, milk, hides, and draft power on demand." },
  { id: "polished-stone", name: "Polished Stone Axes", era: "neolithic", category: "tools",
    year: "~10 kya", prereqs: ["ground-stone"],
    desc: "Ground and polished stone heads — durable enough to fell large trees and clear forest for fields." },
  { id: "pottery", name: "Pottery", era: "neolithic", category: "tools",
    year: "~10 kya", prereqs: ["cooking", "basketry"],
    desc: "Fired clay vessels for cooking, fermentation, and storage. Independently invented many times." },
  { id: "village", name: "Permanent Villages", era: "neolithic", category: "shelter",
    year: "~10 kya", prereqs: ["semi-sedentism", "plant-cultivation"],
    desc: "Mudbrick and timber settlements (Jericho, Çatalhöyük). Hundreds to thousands of residents." },
  { id: "adobe-brick", name: "Adobe Brick", era: "neolithic", category: "shelter",
    year: "~10 kya", prereqs: ["pottery", "village"],
    desc: "Sun-dried mud bricks. Standardized building blocks enable larger, more uniform structures." },
  { id: "megaliths", name: "Megalithic Monuments", era: "neolithic", category: "social",
    year: "~11 kya", prereqs: ["village", "trade-networks"],
    desc: "Göbekli Tepe and later stone circles. Communal ritual architecture predating agriculture in some cases." },
  { id: "ritual-religion", name: "Organized Religion", era: "neolithic", category: "social",
    year: "~10 kya", prereqs: ["burial", "megaliths", "shamanism"],
    desc: "Standardized myths, calendars, and ritual specialists serving settled communities. The shift from animism to gods." },
  { id: "pottery-wheel", name: "Pottery Wheel", era: "neolithic", category: "tools",
    year: "~6 kya", prereqs: ["pottery"],
    desc: "Rotating disc for shaping symmetric vessels at speed. The first rotational machine." },
  { id: "weaving", name: "Loom Weaving", era: "neolithic", category: "tools",
    year: "~9 kya", prereqs: ["basketry", "animal-domestication"],
    desc: "Warp-and-weft textiles from flax and wool. Replaces hides for most everyday garments." },
  { id: "domesticated-flax", name: "Flax & Cotton", era: "neolithic", category: "subsistence",
    year: "~9 kya", prereqs: ["plant-cultivation", "weaving"],
    desc: "Fiber crops cultivated for textiles. Frees clothing from animal supply." },
  { id: "irrigation", name: "Irrigation", era: "neolithic", category: "subsistence",
    year: "~8 kya", prereqs: ["village", "plant-cultivation"],
    desc: "Channeled water to fields, multiplying yields in dry regions. The foundation of river-valley civilizations." },
  { id: "plow-ard", name: "Ard Plow", era: "neolithic", category: "subsistence",
    year: "~6 kya", prereqs: ["animal-domestication", "polished-stone"],
    desc: "Animal-drawn scratch plow. Turns soil far faster than digging sticks and opens heavy land." },
  { id: "millstone", name: "Millstone", era: "neolithic", category: "subsistence",
    year: "~9 kya", prereqs: ["ground-stone", "plant-cultivation"],
    desc: "Saddle querns for grinding grain into flour. Daily bread becomes practical." },
  { id: "fermentation-brewing", name: "Fermentation & Brewing", era: "neolithic", category: "subsistence",
    year: "~9 kya", prereqs: ["pottery", "plant-cultivation"],
    desc: "Beer, mead, and bread leavening through controlled microbial action. Calories, calories that keep, and ritual drink." },
  { id: "granary", name: "Granaries & Storage", era: "neolithic", category: "subsistence",
    year: "~9 kya", prereqs: ["plant-cultivation", "pottery"],
    desc: "Dedicated structures for surplus grain. Underwrites population growth and incipient inequality." },
  { id: "sledge-runner", name: "Sledge", era: "neolithic", category: "transport",
    year: "~8 kya", prereqs: ["polished-stone"],
    desc: "Runner-mounted load-haulers pulled over snow, mud, or logs. Predecessor to the wheeled cart." },
  { id: "sail-primitive", name: "Square Sail", era: "neolithic", category: "transport",
    year: "~7 kya", prereqs: ["canoe", "spun-fiber-mat"],
    desc: "Reed-mat or linen sail rigged on a single mast. Wind power supplements paddling on rivers and coasts." },
  { id: "copper-smelting", name: "Copper Smelting", era: "neolithic", category: "tools",
    year: "~7 kya", prereqs: ["pottery", "polished-stone"],
    desc: "Reducing copper ore in clay-lined furnaces. The transition from stone to metal." },
  { id: "mathematics-counting", name: "Counting Systems", era: "neolithic", category: "knowledge",
    year: "~9 kya", prereqs: ["tally-bones", "granary"],
    desc: "Standardized numerals tied to grain and livestock accounting. Numbers as a tool of trade." },
  { id: "proto-writing-tokens", name: "Proto-Writing", era: "neolithic", category: "communication",
    year: "~8 kya", prereqs: ["mathematics-counting", "granary"],
    desc: "Clay tokens, bullae, and pictographs recording inventories. Writing born from accounting." },

  // ─── Bronze Age ────────────────────────────────────────────────
  { id: "bronze-metallurgy", name: "Bronze Metallurgy", era: "bronze", category: "tools",
    year: "~3300 BCE", prereqs: ["copper-smelting"],
    desc: "Tin-copper alloy harder than either parent. Defines an age and reshapes warfare, agriculture, and trade." },
  { id: "bronze-tools", name: "Bronze Tools", era: "bronze", category: "tools",
    year: "~3200 BCE", prereqs: ["bronze-metallurgy"],
    desc: "Bronze axes, chisels, saws, and sickles. Wood and stoneworking accelerate dramatically." },
  { id: "bronze-weapons", name: "Bronze Weapons", era: "bronze", category: "weapons",
    year: "~3200 BCE", prereqs: ["bronze-metallurgy", "composite-spear"],
    desc: "Cast bronze swords, daggers, and spear points. Stone weapons become obsolete on the battlefield." },
  { id: "iron-meteoric", name: "Meteoric Iron", era: "bronze", category: "tools",
    year: "~3200 BCE", prereqs: ["bronze-metallurgy"],
    desc: "Cold-worked iron from meteorites (Tutankhamun's dagger). Rare and prestigious before smelting was understood." },
  { id: "spoked-wheel", name: "Spoked Wheel", era: "bronze", category: "transport",
    year: "~3500 BCE", prereqs: ["pottery-wheel", "sledge-runner"],
    desc: "Lighter, faster wheels with hub and spokes. Replaces solid disc wheels for transport." },
  { id: "wheeled-cart", name: "Wheeled Cart", era: "bronze", category: "transport",
    year: "~3500 BCE", prereqs: ["spoked-wheel", "animal-domestication"],
    desc: "Ox- and donkey-drawn carts. Land freight throughput increases by an order of magnitude." },
  { id: "horse-domestication", name: "Horse Domestication", era: "bronze", category: "transport",
    year: "~3500 BCE", prereqs: ["animal-domestication"],
    desc: "Tamed steppe horses (Botai). Speed, range, and traction transform mobility, war, and herding." },
  { id: "chariot", name: "War Chariot", era: "bronze", category: "weapons",
    year: "~2000 BCE", prereqs: ["wheeled-cart", "horse-domestication", "bronze-metallurgy"],
    desc: "Two-horse fighting platform. Dominates Bronze Age battlefields from Mycenae to Shang China." },
  { id: "composite-bow", name: "Composite Bow", era: "bronze", category: "weapons",
    year: "~2000 BCE", prereqs: ["bow-arrow", "hafting"],
    desc: "Layered horn, wood, and sinew bow. Short enough for horseback, powerful enough to pierce armor." },
  { id: "city-state", name: "City-State", era: "bronze", category: "economy",
    year: "~3500 BCE", prereqs: ["village", "irrigation"],
    desc: "Walled urban centers governing surrounding farmland. Sumerian Uruk is the prototype." },
  { id: "code-of-law", name: "Codified Law", era: "bronze", category: "economy",
    year: "~2100 BCE", prereqs: ["city-state", "proto-writing-tokens"],
    desc: "Written legal codes (Ur-Nammu, Hammurabi). Public, predictable rules replace personal arbitration." },
  { id: "cuneiform", name: "Cuneiform", era: "bronze", category: "communication",
    year: "~3200 BCE", prereqs: ["proto-writing-tokens"],
    desc: "Wedge-shaped Sumerian script on clay tablets. The first fully developed writing system." },
  { id: "hieroglyphics", name: "Hieroglyphics", era: "bronze", category: "communication",
    year: "~3200 BCE", prereqs: ["proto-writing-tokens"],
    desc: "Egyptian pictographic and phonetic script carved in stone and inked on papyrus." },
  { id: "alphabet-phoenician", name: "Phoenician Alphabet", era: "bronze", category: "communication",
    year: "~1200 BCE", prereqs: ["cuneiform"],
    desc: "Twenty-two consonant signs. Writing becomes learnable in weeks instead of years." },
  { id: "abacus", name: "Abacus", era: "bronze", category: "knowledge",
    year: "~2700 BCE", prereqs: ["mathematics-counting"],
    desc: "Bead-and-rod calculating frame. Mechanizes addition and multiplication for traders and scribes." },
  { id: "mathematics-arithmetic", name: "Arithmetic", era: "bronze", category: "knowledge",
    year: "~2000 BCE", prereqs: ["cuneiform", "mathematics-counting"],
    desc: "Babylonian sexagesimal arithmetic, fractions, and quadratic methods. Math as a written discipline." },
  { id: "astronomy-observation", name: "Astronomy", era: "bronze", category: "knowledge",
    year: "~1800 BCE", prereqs: ["lunar-tally", "mathematics-arithmetic"],
    desc: "Systematic recording of planetary motion. Babylonian tablets predict eclipses centuries ahead." },
  { id: "solar-calendar", name: "Solar Calendar", era: "bronze", category: "knowledge",
    year: "~3000 BCE", prereqs: ["astronomy-observation"],
    desc: "365-day Egyptian calendar tied to Nile flooding and Sirius. Civil time decoupled from the moon." },
  { id: "monumental-architecture", name: "Monumental Architecture", era: "bronze", category: "shelter",
    year: "~3000 BCE", prereqs: ["megaliths", "city-state"],
    desc: "Temples and palaces built with planned engineering and mass labor. Architecture as state propaganda." },
  { id: "pyramid-ziggurat", name: "Pyramids & Ziggurats", era: "bronze", category: "shelter",
    year: "~2600 BCE", prereqs: ["monumental-architecture", "mathematics-arithmetic"],
    desc: "Stepped and smooth-sided mountains of stone and brick. Tombs, temples, and statements of cosmic order." },
  { id: "glass-making", name: "Glass Making", era: "bronze", category: "tools",
    year: "~3500 BCE", prereqs: ["pottery", "copper-smelting"],
    desc: "Fused silica beads and vessels. A new transparent material with profound future uses." },
  { id: "silver-gold-metallurgy", name: "Precious Metals", era: "bronze", category: "tools",
    year: "~3000 BCE", prereqs: ["copper-smelting"],
    desc: "Refining and working silver, gold, and electrum. Stores of value and ornament." },
  { id: "olive-wine", name: "Olive Oil & Wine", era: "bronze", category: "subsistence",
    year: "~3000 BCE", prereqs: ["plant-cultivation", "pottery"],
    desc: "Tree-crop horticulture and fermentation. Mediterranean staples that travel and trade well." },
  { id: "linen-textile", name: "Linen Textiles", era: "bronze", category: "tools",
    year: "~3000 BCE", prereqs: ["weaving", "domesticated-flax"],
    desc: "Bleached flax fabrics for clothing, sails, and trade. The premier textile of the ancient world." },
  { id: "standing-army", name: "Standing Army", era: "bronze", category: "weapons",
    year: "~2300 BCE", prereqs: ["city-state", "bronze-weapons"],
    desc: "Full-time professional soldiers (Akkadian Empire). Permanent military force replaces seasonal levies." },
  { id: "maritime-trade", name: "Maritime Trade", era: "bronze", category: "economy",
    year: "~3000 BCE", prereqs: ["sail-primitive", "city-state"],
    desc: "Cross-sea exchange of tin, copper, oil, and grain. Bronze itself depends on long-haul shipping." },
  { id: "galley-ship", name: "Galley", era: "bronze", category: "transport",
    year: "~3000 BCE", prereqs: ["sail-primitive", "bronze-tools"],
    desc: "Oared and sailed warship and trader. Multi-decked Phoenician galleys cross the Mediterranean." },
  { id: "pulley-lever", name: "Pulley & Lever", era: "bronze", category: "tools",
    year: "~2000 BCE", prereqs: ["monumental-architecture", "mathematics-arithmetic"],
    desc: "Simple machines for lifting stone and water. Mechanical advantage formalized." },
  { id: "proto-medicine", name: "Temple Medicine", era: "bronze", category: "medicine",
    year: "~1800 BCE", prereqs: ["ritual-religion", "cuneiform"],
    desc: "Edwin Smith Papyrus and Babylonian diagnostic texts. Empirical observation entwined with ritual." },
  { id: "trepanation", name: "Trepanation", era: "bronze", category: "medicine",
    year: "~7000 BCE", prereqs: ["polished-stone", "ritual-religion"],
    desc: "Surgical drilling of skull holes. Many patients survived — the first attested major surgery." },

  // ─── Classical Antiquity ───────────────────────────────────────
  { id: "iron-smelting", name: "Iron Smelting", era: "classical", category: "tools",
    year: "~1200 BCE", prereqs: ["bronze-metallurgy", "glass-making"],
    desc: "Bloomery smelting of iron ore. Iron is common where tin is not — democratizes metal." },
  { id: "iron-tools", name: "Iron Tools", era: "classical", category: "tools",
    year: "~1100 BCE", prereqs: ["iron-smelting"],
    desc: "Iron axes, plowshares, and saws. Tougher and cheaper than bronze, available to ordinary farmers." },
  { id: "iron-weapons", name: "Iron Weapons", era: "classical", category: "weapons",
    year: "~1100 BCE", prereqs: ["iron-smelting", "bronze-weapons"],
    desc: "Iron swords, spears, and arrowheads. Cheap edge ends bronze-age power balances." },
  { id: "steel-bloomery", name: "Bloomery Steel", era: "classical", category: "tools",
    year: "~600 BCE", prereqs: ["iron-smelting"],
    desc: "Carburized iron sponge worked into steel. Indian wootz and Chinese cast iron lead the way." },
  { id: "alphabet-greek", name: "Greek Alphabet", era: "classical", category: "communication",
    year: "~800 BCE", prereqs: ["alphabet-phoenician"],
    desc: "Phoenician script with vowels added. The basis of every Western alphabet." },
  { id: "alphabet-latin", name: "Latin Alphabet", era: "classical", category: "communication",
    year: "~700 BCE", prereqs: ["alphabet-greek"],
    desc: "Roman adaptation of Greek letters. Carried by empire to dominate Western writing." },
  { id: "philosophy", name: "Philosophy", era: "classical", category: "knowledge",
    year: "~600 BCE", prereqs: ["alphabet-greek", "mathematics-arithmetic"],
    desc: "Systematic inquiry into being, ethics, and knowledge. From Thales to Confucius to the Buddha." },
  { id: "geometry-euclidean", name: "Euclidean Geometry", era: "classical", category: "knowledge",
    year: "~300 BCE", prereqs: ["mathematics-arithmetic", "philosophy"],
    desc: "Axiomatic deductive proof in Euclid's Elements. The model for rigorous reasoning for 2000 years." },
  { id: "zero-numeral", name: "Zero as Numeral", era: "classical", category: "knowledge",
    year: "~500 CE", prereqs: ["philosophy", "mathematics-arithmetic"],
    desc: "Indian Brahmagupta treats zero as a number with rules. Unlocks place-value arithmetic." },
  { id: "alchemy", name: "Alchemy", era: "classical", category: "knowledge",
    year: "~300 BCE", prereqs: ["glass-making", "philosophy"],
    desc: "Hellenistic and Chinese material experimentation. Mystical aims, but practical metallurgy and chemistry result." },
  { id: "coinage", name: "Coinage", era: "classical", category: "economy",
    year: "~700 BCE", prereqs: ["silver-gold-metallurgy", "code-of-law"],
    desc: "Stamped metal money of guaranteed weight (Lydia). Standardizes value and accelerates trade." },
  { id: "democracy", name: "Democracy", era: "classical", category: "economy",
    year: "~500 BCE", prereqs: ["city-state", "code-of-law", "philosophy"],
    desc: "Athenian rule by citizen assembly. Direct vote on laws and magistracies." },
  { id: "republic", name: "Republic", era: "classical", category: "economy",
    year: "~500 BCE", prereqs: ["democracy"],
    desc: "Representative government under elected magistrates and a senate. Roman Republic the most influential model." },
  { id: "empire", name: "Empire", era: "classical", category: "economy",
    year: "~550 BCE", prereqs: ["standing-army", "coinage", "code-of-law"],
    desc: "Multi-ethnic territorial states (Achaemenid, Han, Roman). Roads, currency, and bureaucracy at continental scale." },
  { id: "roman-law", name: "Roman Law", era: "classical", category: "economy",
    year: "~450 BCE", prereqs: ["code-of-law", "empire"],
    desc: "Twelve Tables through Justinian's Corpus. The grammar of Western private and public law." },
  { id: "roads-paved", name: "Paved Roads", era: "classical", category: "transport",
    year: "~300 BCE", prereqs: ["empire", "monumental-architecture"],
    desc: "Multi-layered Roman viae and Persian Royal Road. All-weather networks bind empires together." },
  { id: "aqueduct", name: "Aqueduct", era: "classical", category: "shelter",
    year: "~700 BCE", prereqs: ["monumental-architecture", "mathematics-arithmetic"],
    desc: "Gravity-fed water channels carrying potable water tens of kilometers. Cities outgrow local wells." },
  { id: "arch-vault", name: "Arch & Vault", era: "classical", category: "shelter",
    year: "~500 BCE", prereqs: ["monumental-architecture", "geometry-euclidean"],
    desc: "Compression-loaded stone arches. Allow large unsupported spans — basilicas, baths, bridges." },
  { id: "concrete-roman", name: "Roman Concrete", era: "classical", category: "tools",
    year: "~200 BCE", prereqs: ["aqueduct", "arch-vault"],
    desc: "Pozzolana-lime hydraulic cement. Sets underwater, lasts millennia (Pantheon dome)." },
  { id: "crossbow", name: "Crossbow", era: "classical", category: "weapons",
    year: "~500 BCE", prereqs: ["composite-bow", "iron-tools"],
    desc: "Mechanically drawn bow with stock and trigger. Trains a peasant in a day to defeat a knight." },
  { id: "siege-engine", name: "Siege Engines", era: "classical", category: "weapons",
    year: "~400 BCE", prereqs: ["pulley-lever", "iron-tools", "geometry-euclidean"],
    desc: "Torsion catapults, ballistae, and rams. Walls become a problem to be engineered against." },
  { id: "cavalry", name: "Heavy Cavalry", era: "classical", category: "weapons",
    year: "~600 BCE", prereqs: ["horse-domestication", "iron-weapons"],
    desc: "Mailed riders charging with lance and sword. Steppe and Iranian innovation that displaces chariots." },
  { id: "saddle-stirrup", name: "Saddle & Stirrup", era: "classical", category: "transport",
    year: "~400 CE", prereqs: ["horse-domestication", "iron-tools"],
    desc: "Framed saddle and metal foot loops. Stable mounted combat — the rider becomes a weapons platform." },
  { id: "silk-production", name: "Silk Production", era: "classical", category: "tools",
    year: "~2700 BCE", prereqs: ["animal-domestication", "weaving"],
    desc: "Cultivation of silkworms and reeling of cocoons. China's monopoly drives Eurasian trade." },
  { id: "paper-making", name: "Paper", era: "classical", category: "communication",
    year: "~100 CE", prereqs: ["silk-production", "linen-textile"],
    desc: "Pulped fiber pressed into sheets (Cai Lun). Cheaper and lighter than papyrus or parchment." },
  { id: "world-religion", name: "World Religions", era: "classical", category: "social",
    year: "~500 BCE", prereqs: ["ritual-religion", "alphabet-phoenician", "empire"],
    desc: "Buddhism, Christianity, Judaism, and Zoroastrianism crystallize. Universal moral codes transcending tribe." },
  { id: "monasticism", name: "Monasticism", era: "classical", category: "social",
    year: "~300 CE", prereqs: ["world-religion", "alphabet-latin"],
    desc: "Communities devoted to prayer, study, and labor. The institutional preserver of literacy through dark ages." },
  { id: "library", name: "Libraries", era: "classical", category: "knowledge",
    year: "~300 BCE", prereqs: ["alphabet-phoenician", "paper-making"],
    desc: "Alexandria, Pergamon, Nalanda. State-curated collections of scrolls and codices." },
  { id: "scientific-method-proto", name: "Proto-Science", era: "classical", category: "knowledge",
    year: "~300 BCE", prereqs: ["philosophy", "geometry-euclidean"],
    desc: "Aristotle's natural philosophy and Alexandrian empiricism. Observation organized but not yet experimental." },
  { id: "medicine-galenic", name: "Galenic Medicine", era: "classical", category: "medicine",
    year: "~150 CE", prereqs: ["proto-medicine", "philosophy"],
    desc: "Hippocratic and Galenic humoral theory plus systematic anatomy. Dominates medicine for 1500 years." },
  { id: "water-clock", name: "Water Clock", era: "classical", category: "knowledge",
    year: "~300 BCE", prereqs: ["pulley-lever", "mathematics-arithmetic"],
    desc: "Clepsydra timing by regulated water flow. Independent of sun and visible from indoors." },
  { id: "waterwheel", name: "Waterwheel", era: "classical", category: "energy",
    year: "~200 BCE", prereqs: ["pulley-lever", "iron-tools"],
    desc: "Vertical and horizontal water-driven mills. The first mechanical replacement for human muscle." },
  { id: "compass-early", name: "Lodestone Compass", era: "classical", category: "knowledge",
    year: "~200 BCE", prereqs: ["iron-smelting", "philosophy"],
    desc: "Han Chinese magnetic spoons used for divination. The instrument finds direction long before it finds ships." },
  { id: "triremes", name: "Triremes", era: "classical", category: "transport",
    year: "~700 BCE", prereqs: ["galley-ship", "iron-tools"],
    desc: "Three-banked oared warships with bronze rams. Naval supremacy is born." },
  { id: "gear-mechanism", name: "Gear Mechanism", era: "classical", category: "tools",
    year: "~200 BCE", prereqs: ["pulley-lever", "iron-tools"],
    desc: "Toothed wheels transmitting and stepping rotation (Antikythera mechanism). Mechanical computation appears." },
  { id: "woodblock-printing", name: "Woodblock Printing", era: "classical", category: "communication",
    year: "~200 CE", prereqs: ["paper-making", "alphabet-greek"],
    desc: "Carved wood blocks inked and pressed onto paper. Mass duplication of texts and images, especially in Tang China." },

  // ─── Medieval ──────────────────────────────────────────────────
  { id: "arabic-numerals", name: "Hindu-Arabic Numerals", era: "medieval", category: "knowledge",
    year: "~800 CE", prereqs: ["zero-numeral"],
    desc: "Place-value digits 0–9 transmitted through the Islamic world. Calculation outpaces Roman numerals tenfold." },
  { id: "algebra", name: "Algebra", era: "medieval", category: "knowledge",
    year: "~825 CE", prereqs: ["arabic-numerals", "geometry-euclidean"],
    desc: "Al-Khwarizmi's symbolic equation solving. The word algorithm comes from his name." },
  { id: "gunpowder", name: "Gunpowder", era: "medieval", category: "weapons",
    year: "~850 CE", prereqs: ["alchemy"],
    desc: "Saltpeter, sulfur, and charcoal. Tang Daoist alchemists discover the chemistry that ends castle warfare." },
  { id: "moveable-type", name: "Moveable Type", era: "medieval", category: "communication",
    year: "~1040 CE", prereqs: ["woodblock-printing"],
    desc: "Bi Sheng's individual ceramic characters. The principle of recombinable type." },
  { id: "mechanical-clock", name: "Mechanical Clock", era: "medieval", category: "knowledge",
    year: "~1300 CE", prereqs: ["water-clock", "gear-mechanism", "iron-tools"],
    desc: "Verge-and-foliot escapement striking bells. European cities shift from sun-time to scheduled time." },
  { id: "windmill", name: "Windmill", era: "medieval", category: "energy",
    year: "~700 CE", prereqs: ["waterwheel", "sail-primitive"],
    desc: "Persian and European wind-driven mills. Mechanical power away from rivers." },
  { id: "heavy-plow", name: "Heavy Plow", era: "medieval", category: "subsistence",
    year: "~600 CE", prereqs: ["plow-ard", "iron-tools"],
    desc: "Mouldboard plow with iron coulter and share. Turns the wet, heavy clays of northern Europe into farmland." },
  { id: "horse-collar", name: "Horse Collar", era: "medieval", category: "subsistence",
    year: "~800 CE", prereqs: ["horse-domestication", "iron-tools"],
    desc: "Padded shoulder harness that doesn't choke the animal. Horses out-pull oxen for the first time." },
  { id: "three-field-system", name: "Three-Field System", era: "medieval", category: "subsistence",
    year: "~800 CE", prereqs: ["heavy-plow", "horse-collar"],
    desc: "Crop rotation among winter, spring, and fallow fields. European yields jump 30–50%." },
  { id: "university", name: "University", era: "medieval", category: "knowledge",
    year: "~1088 CE", prereqs: ["monasticism", "library"],
    desc: "Bologna, Paris, Oxford. Self-governing corporations of scholars with degrees and faculties." },
  { id: "scholasticism", name: "Scholasticism", era: "medieval", category: "knowledge",
    year: "~1100 CE", prereqs: ["university", "philosophy"],
    desc: "Aquinas's reconciliation of Aristotle with theology. Disputation as the engine of medieval thought." },
  { id: "gothic-architecture", name: "Gothic Architecture", era: "medieval", category: "shelter",
    year: "~1150 CE", prereqs: ["arch-vault", "geometry-euclidean"],
    desc: "Pointed arches, ribbed vaults, flying buttresses. Stone walls dissolve into glass — Notre-Dame, Chartres." },
  { id: "castle", name: "Castle", era: "medieval", category: "shelter",
    year: "~900 CE", prereqs: ["monumental-architecture", "iron-tools"],
    desc: "Stone fortifications integrating residence and garrison. The instrument of feudal territorial control." },
  { id: "knight-cavalry", name: "Mounted Knight", era: "medieval", category: "weapons",
    year: "~900 CE", prereqs: ["cavalry", "saddle-stirrup", "iron-weapons"],
    desc: "Plate-armored noble cavalry with couched lance. The shock arm of feudal armies for 600 years." },
  { id: "longbow", name: "Longbow", era: "medieval", category: "weapons",
    year: "~1300 CE", prereqs: ["bow-arrow", "iron-tools"],
    desc: "Six-foot Welsh war bow. Cheap, fast, and capable of punching through plate at Crécy and Agincourt." },
  { id: "cannon-early", name: "Cannon", era: "medieval", category: "weapons",
    year: "~1300 CE", prereqs: ["gunpowder", "iron-smelting"],
    desc: "Cast tubes firing stone or iron shot. The end of the impregnable castle." },
  { id: "caravel", name: "Caravel", era: "medieval", category: "transport",
    year: "~1450 CE", prereqs: ["galley-ship", "sail-primitive", "compass-early"],
    desc: "Lateen-rigged Iberian ship that sails close to the wind. The vessel of the Age of Discovery." },
  { id: "hospital", name: "Hospital", era: "medieval", category: "medicine",
    year: "~700 CE", prereqs: ["medicine-galenic", "world-religion"],
    desc: "Islamic bimaristans and Christian xenodochia. Institutional care for the sick separate from private homes." },
  { id: "guild", name: "Guild", era: "medieval", category: "economy",
    year: "~1100 CE", prereqs: ["city-state", "world-religion"],
    desc: "Sworn craft and merchant associations. Set quality, prices, and apprenticeship — proto-corporations." },
  { id: "banking-double-entry", name: "Double-Entry Banking", era: "medieval", category: "economy",
    year: "~1300 CE", prereqs: ["arabic-numerals", "coinage"],
    desc: "Italian merchant ledgers tracking debits and credits. Errors become detectable and audits possible." },
  { id: "letter-of-credit", name: "Letter of Credit", era: "medieval", category: "economy",
    year: "~1200 CE", prereqs: ["banking-double-entry", "paper-making"],
    desc: "Bills of exchange replacing physical gold on long routes. Banking goes international." },
  { id: "magnetic-compass-marine", name: "Marine Compass", era: "medieval", category: "transport",
    year: "~1100 CE", prereqs: ["compass-early", "caravel"],
    desc: "Magnetized needle on a card, sealed in a binnacle. Open-ocean navigation independent of sun and stars." },
  { id: "glass-lens", name: "Glass Lens", era: "medieval", category: "knowledge",
    year: "~1000 CE", prereqs: ["glass-making"],
    desc: "Ground convex lenses for reading and burning. Ibn al-Haytham's optics formalizes the field." },
  { id: "spectacles", name: "Spectacles", era: "medieval", category: "medicine",
    year: "~1290 CE", prereqs: ["glass-lens"],
    desc: "Italian reading glasses extending the working life of scholars and craftsmen by decades." },
  { id: "distillation", name: "Distillation", era: "medieval", category: "knowledge",
    year: "~800 CE", prereqs: ["alchemy", "glass-making"],
    desc: "Alembic separation of liquids by boiling point. Spirits, perfumes, and the chemical lab." },
  { id: "paper-mill", name: "Paper Mill", era: "medieval", category: "communication",
    year: "~1100 CE", prereqs: ["paper-making", "waterwheel"],
    desc: "Water-powered hammer mills pulping rags. Paper costs collapse — a precondition for printing." },
  { id: "horizontal-loom", name: "Horizontal Loom", era: "medieval", category: "tools",
    year: "~1000 CE", prereqs: ["weaving", "gear-mechanism"],
    desc: "Treadle-operated loom freeing both hands. Cloth output rises tenfold over the warp-weighted loom." },
  { id: "quill-ink", name: "Quill & Ink", era: "medieval", category: "communication",
    year: "~600 CE", prereqs: ["paper-making"],
    desc: "Goose-feather pens with iron-gall ink on parchment. The standard writing technology for a millennium." },

  // ─── Renaissance ───────────────────────────────────────────────
  { id: "printing-press", name: "Printing Press", era: "renaissance", category: "communication",
    year: "1450", prereqs: ["moveable-type", "paper-mill"],
    desc: "Gutenberg's screw press with metal type. Books drop in price 100×; ideas propagate at unprecedented speed." },
  { id: "vernacular-literature", name: "Vernacular Literature", era: "renaissance", category: "social",
    year: "1300–1500", prereqs: ["printing-press", "alphabet-latin"],
    desc: "Dante, Chaucer, Cervantes write in spoken languages. Reading audiences expand beyond clerical Latin." },
  { id: "humanism", name: "Humanism", era: "renaissance", category: "social",
    year: "1400", prereqs: ["vernacular-literature", "scholasticism"],
    desc: "Recovery and study of classical texts. The dignity and capacity of the individual person becomes central." },
  { id: "linear-perspective", name: "Linear Perspective", era: "renaissance", category: "social",
    year: "1420", prereqs: ["geometry-euclidean", "vernacular-literature"],
    desc: "Brunelleschi and Alberti formalize geometric depth. Painting becomes a window onto rationalized space." },
  { id: "oil-painting", name: "Oil Painting", era: "renaissance", category: "social",
    year: "1430", prereqs: ["pigments", "linear-perspective"],
    desc: "Linseed-oil binders allowing slow, layered glazes. Van Eyck and successors achieve photographic luminosity." },
  { id: "opera-orchestra", name: "Opera & Orchestra", era: "renaissance", category: "social",
    year: "1600", prereqs: ["vernacular-literature"],
    desc: "Sung drama with instrumental ensembles. Monteverdi launches a 400-year tradition of large-scale music." },
  { id: "scientific-method", name: "Scientific Method", era: "renaissance", category: "knowledge",
    year: "1620", prereqs: ["scientific-method-proto", "printing-press", "glass-lens"],
    desc: "Bacon's induction and Galileo's experiment. Test, measure, and publish — knowledge by demonstration." },
  { id: "heliocentrism", name: "Heliocentrism", era: "renaissance", category: "knowledge",
    year: "1543", prereqs: ["astronomy-observation", "mathematics-arithmetic", "printing-press"],
    desc: "Copernicus puts the sun at the center; Kepler describes elliptical orbits. The Earth is no longer special." },
  { id: "algebra-symbolic", name: "Symbolic Algebra", era: "renaissance", category: "knowledge",
    year: "1591", prereqs: ["algebra", "printing-press"],
    desc: "Viète's letters for unknowns and constants. Equations become manipulable in the form we still use." },
  { id: "logarithms", name: "Logarithms", era: "renaissance", category: "knowledge",
    year: "1614", prereqs: ["algebra-symbolic", "mathematics-arithmetic"],
    desc: "Napier's tables turning multiplication into addition. Pre-electronic calculation accelerates by orders of magnitude." },
  { id: "anatomy-vesalius", name: "Modern Anatomy", era: "renaissance", category: "medicine",
    year: "1543", prereqs: ["medicine-galenic", "printing-press"],
    desc: "Vesalius dissects and corrects Galen with detailed engravings. Medicine grounded in observed structure." },
  { id: "microscope", name: "Microscope", era: "renaissance", category: "knowledge",
    year: "1620", prereqs: ["glass-lens", "spectacles"],
    desc: "Compound lenses revealing cells and microbes. A whole new biological domain becomes visible." },
  { id: "telescope", name: "Telescope", era: "renaissance", category: "knowledge",
    year: "1608", prereqs: ["glass-lens", "heliocentrism"],
    desc: "Galileo's lens-tube reveals Jupiter's moons and Venus's phases. The naked-eye sky stops being enough." },
  { id: "pendulum-clock", name: "Pendulum Clock", era: "renaissance", category: "knowledge",
    year: "1656", prereqs: ["mechanical-clock", "mathematics-arithmetic"],
    desc: "Huygens's isochronous pendulum reaches seconds-per-day accuracy. Science gains a precise time standard." },
  { id: "protestant-reformation", name: "Protestant Reformation", era: "renaissance", category: "social",
    year: "1517", prereqs: ["printing-press", "world-religion"],
    desc: "Luther's theses spread by press. Splits Western Christianity and seeds religious pluralism and literacy." },
  { id: "nation-state", name: "Nation-State", era: "renaissance", category: "economy",
    year: "1500", prereqs: ["empire", "printing-press"],
    desc: "Centralized monarchies with permanent bureaucracies and standing taxes. The territorial unit of modernity." },
  { id: "joint-stock-company", name: "Joint-Stock Company", era: "renaissance", category: "economy",
    year: "1600", prereqs: ["banking-double-entry", "nation-state"],
    desc: "Pooled tradable shares (Dutch and English East India Companies). Capital and risk for ventures beyond any individual." },
  { id: "mercantilism", name: "Mercantilism", era: "renaissance", category: "economy",
    year: "1550", prereqs: ["nation-state", "maritime-trade"],
    desc: "State policy maximizing bullion through trade surplus and tariffs. Drives colonial expansion." },
  { id: "galleon", name: "Galleon", era: "renaissance", category: "transport",
    year: "1500", prereqs: ["caravel", "cannon-early"],
    desc: "Multi-decked ocean-going warship and trader. Carries silver from Acapulco to Manila — globalized cargo." },
  { id: "ocean-navigation", name: "Ocean Navigation", era: "renaissance", category: "transport",
    year: "1500", prereqs: ["magnetic-compass-marine", "galleon", "astronomy-observation"],
    desc: "Quadrant, astrolabe, and rutter combined. Reliable open-sea voyages of months at a time." },
  { id: "new-world-encounter", name: "New World Encounter", era: "renaissance", category: "social",
    year: "1492", prereqs: ["ocean-navigation"],
    desc: "Sustained Old-New World contact. Reshapes biology, demography, and economics on every continent." },
  { id: "colonialism", name: "Colonialism", era: "renaissance", category: "economy",
    year: "1500", prereqs: ["new-world-encounter", "mercantilism", "gunpowder"],
    desc: "Extractive overseas empires. Plantation labor, conquest, and forced trade reshape Africa, Asia, and the Americas." },
  { id: "columbian-exchange", name: "Columbian Exchange", era: "renaissance", category: "subsistence",
    year: "1500", prereqs: ["new-world-encounter"],
    desc: "Potatoes, maize, tomatoes, horses, smallpox, syphilis cross oceans. Diet and demography of the world transformed." },
  { id: "musket", name: "Musket", era: "renaissance", category: "weapons",
    year: "1500", prereqs: ["gunpowder", "cannon-early"],
    desc: "Hand-held matchlock and flintlock firearm. Trains a peasant in a week to kill a knight." },
  { id: "artillery", name: "Field Artillery", era: "renaissance", category: "weapons",
    year: "1500", prereqs: ["cannon-early", "mathematics-arithmetic"],
    desc: "Mobile bronze and iron cannon firing on calculated trajectories. Battlefield range extends past bowshot." },
  { id: "bastion-fortification", name: "Bastion Fort", era: "renaissance", category: "shelter",
    year: "1530", prereqs: ["artillery", "geometry-euclidean"],
    desc: "Star-shaped low earthworks resistant to cannon. Sieges become geometry problems." },

  // ─── Enlightenment ─────────────────────────────────────────────
  { id: "newtonian-mechanics", name: "Newtonian Mechanics", era: "enlightenment", category: "knowledge",
    year: "1687", prereqs: ["scientific-method", "heliocentrism", "logarithms"],
    desc: "Three laws plus universal gravitation in the Principia. The planets and the cannonball share one math." },
  { id: "calculus", name: "Calculus", era: "enlightenment", category: "knowledge",
    year: "1684", prereqs: ["algebra-symbolic", "newtonian-mechanics"],
    desc: "Newton and Leibniz independently invent differentiation and integration. The language of continuous change." },
  { id: "gravitation-law", name: "Universal Gravitation", era: "enlightenment", category: "knowledge",
    year: "1687", prereqs: ["newtonian-mechanics", "calculus"],
    desc: "Inverse-square attraction unifying terrestrial and celestial mechanics. Predicts tides, comets, and Neptune." },
  { id: "cartesian-coordinates", name: "Cartesian Coordinates", era: "enlightenment", category: "knowledge",
    year: "1637", prereqs: ["algebra-symbolic", "geometry-euclidean"],
    desc: "Descartes fuses algebra with geometry. Curves become equations and equations become curves." },
  { id: "probability-theory", name: "Probability Theory", era: "enlightenment", category: "knowledge",
    year: "1654", prereqs: ["algebra-symbolic"],
    desc: "Pascal-Fermat correspondence on dice. Reasoning about chance becomes mathematical." },
  { id: "thermometer", name: "Thermometer", era: "enlightenment", category: "knowledge",
    year: "1714", prereqs: ["glass-lens", "scientific-method"],
    desc: "Mercury-in-glass instruments with reproducible scales (Fahrenheit, Celsius). Temperature becomes measurable." },
  { id: "barometer", name: "Barometer", era: "enlightenment", category: "knowledge",
    year: "1643", prereqs: ["glass-lens", "scientific-method"],
    desc: "Torricelli's mercury column measures air pressure. Weather forecasting and the existence of vacuum." },
  { id: "germ-precursor", name: "Microbial Discovery", era: "enlightenment", category: "medicine",
    year: "1676", prereqs: ["microscope", "anatomy-vesalius"],
    desc: "Leeuwenhoek's animalcules. The microbial world is seen but not yet linked to disease." },
  { id: "vaccination", name: "Vaccination", era: "enlightenment", category: "medicine",
    year: "1796", prereqs: ["germ-precursor"],
    desc: "Jenner's cowpox inoculation against smallpox. Deliberate immunity decades before germs are understood." },
  { id: "chemistry-modern", name: "Modern Chemistry", era: "enlightenment", category: "knowledge",
    year: "1789", prereqs: ["alchemy", "scientific-method"],
    desc: "Lavoisier's conservation of mass and oxygen theory. Alchemy becomes a quantitative science." },
  { id: "electricity-static", name: "Static Electricity", era: "enlightenment", category: "knowledge",
    year: "1750", prereqs: ["scientific-method", "chemistry-modern"],
    desc: "Franklin's lightning experiments and Leyden jars. A new fundamental phenomenon to explain." },
  { id: "steam-pump", name: "Atmospheric Steam Engine", era: "enlightenment", category: "energy",
    year: "1712", prereqs: ["mechanical-clock", "gunpowder"],
    desc: "Newcomen's piston pump for draining mines. Heat does work — a new prime mover." },
  { id: "steam-engine-watt", name: "Watt Steam Engine", era: "enlightenment", category: "energy",
    year: "1776", prereqs: ["steam-pump", "calculus"],
    desc: "Separate condenser, governor, and rotary motion. 4× the efficiency — drives the Industrial Revolution." },
  { id: "coke-iron", name: "Coke-Smelted Iron", era: "enlightenment", category: "tools",
    year: "1709", prereqs: ["iron-smelting", "scientific-method"],
    desc: "Darby's coke-fired blast furnace replaces charcoal. Iron production unhitched from forest depletion." },
  { id: "canal-system", name: "Canal Network", era: "enlightenment", category: "transport",
    year: "1761", prereqs: ["arch-vault", "mathematics-arithmetic"],
    desc: "Locked artificial waterways (Bridgewater, Erie). Bulk freight at 1/10 the cost of road haulage." },
  { id: "turnpike-roads", name: "Turnpike Roads", era: "enlightenment", category: "transport",
    year: "1750", prereqs: ["roads-paved", "nation-state"],
    desc: "Toll-funded macadamized highways. Stagecoach travel times in Britain halve in 50 years." },
  { id: "agricultural-revolution", name: "British Agricultural Revolution", era: "enlightenment", category: "subsistence",
    year: "1750", prereqs: ["three-field-system", "columbian-exchange"],
    desc: "Enclosure, new crops, and selective breeding. Yields support an urban industrial workforce." },
  { id: "crop-rotation-norfolk", name: "Norfolk Rotation", era: "enlightenment", category: "subsistence",
    year: "1730", prereqs: ["agricultural-revolution"],
    desc: "Wheat-turnip-barley-clover four-course rotation. Eliminates fallow without depleting soil." },
  { id: "selective-breeding", name: "Scientific Breeding", era: "enlightenment", category: "subsistence",
    year: "1760", prereqs: ["animal-domestication", "scientific-method"],
    desc: "Bakewell's livestock improvement programs. Sheep weight doubles in a generation through pedigreed selection." },
  { id: "enlightenment-philosophy", name: "Enlightenment Philosophy", era: "enlightenment", category: "social",
    year: "1750", prereqs: ["humanism", "scientific-method"],
    desc: "Locke, Voltaire, Kant, Rousseau. Reason, individual rights, religious tolerance, and the social contract." },
  { id: "liberal-democracy", name: "Liberal Democracy", era: "enlightenment", category: "economy",
    year: "1789", prereqs: ["enlightenment-philosophy", "republic"],
    desc: "Constitutional government with civil liberties and representative legislatures. American and French revolutions." },
  { id: "separation-of-powers", name: "Separation of Powers", era: "enlightenment", category: "economy",
    year: "1748", prereqs: ["liberal-democracy", "roman-law"],
    desc: "Montesquieu's tripartite government. Encoded in the U.S. Constitution as checks and balances." },
  { id: "encyclopedia", name: "Encyclopédie", era: "enlightenment", category: "knowledge",
    year: "1751", prereqs: ["enlightenment-philosophy", "printing-press"],
    desc: "Diderot and d'Alembert's 35-volume reference. Knowledge organized for the public, not the academy." },
  { id: "public-education", name: "Public Education", era: "enlightenment", category: "social",
    year: "1763", prereqs: ["encyclopedia", "nation-state"],
    desc: "State-funded universal schooling (Prussia leads). Literacy and numeracy as civic infrastructure." },
  { id: "factory-system", name: "Factory System", era: "enlightenment", category: "economy",
    year: "1780", prereqs: ["steam-engine-watt", "joint-stock-company"],
    desc: "Centralized power-driven workshops with wage labor. Cottage production gives way to the mill town." },
  { id: "spinning-jenny", name: "Spinning Jenny", era: "enlightenment", category: "tools",
    year: "1764", prereqs: ["horizontal-loom", "factory-system"],
    desc: "Multi-spindle hand-cranked spinner. One operator does the work of eight." },
  { id: "power-loom", name: "Power Loom", era: "enlightenment", category: "tools",
    year: "1785", prereqs: ["spinning-jenny", "steam-engine-watt"],
    desc: "Cartwright's steam-driven loom. Cloth becomes the first mass-produced industrial commodity." },
  { id: "naval-warship", name: "Ship of the Line", era: "enlightenment", category: "transport",
    year: "1700", prereqs: ["galleon", "artillery"],
    desc: "Three-decker first-rate firing 100+ broadside guns. Floating fortresses contesting global trade routes." },
  { id: "modern-bookkeeping", name: "Modern Bookkeeping", era: "enlightenment", category: "economy",
    year: "1700", prereqs: ["banking-double-entry", "joint-stock-company"],
    desc: "Standardized profit-and-loss and balance sheets for chartered companies. Financial transparency at scale." },
  { id: "central-bank", name: "Central Bank", era: "enlightenment", category: "economy",
    year: "1694", prereqs: ["banking-double-entry", "nation-state"],
    desc: "Bank of England, then others. State debt, banknotes, and monetary policy in one institution." },

  // ─── Industrial ────────────────────────────────────────────────
  { id: "bessemer-steel", name: "Bessemer Steel", era: "industrial", category: "tools",
    year: "1855", prereqs: ["coke-iron", "steam-engine-watt"],
    desc: "Air-blown converter mass-producing steel from pig iron. Cost falls 80% — rails, ships, skyscrapers become possible." },
  { id: "railway-locomotive", name: "Steam Locomotive", era: "industrial", category: "transport",
    year: "1814", prereqs: ["steam-engine-watt", "bessemer-steel"],
    desc: "Stephenson's Rocket and successors. Inland transport at 50 mph collapses distance and unifies markets." },
  { id: "telegraph", name: "Electric Telegraph", era: "industrial", category: "communication",
    year: "1837", prereqs: ["electricity-static", "electromagnetism"],
    desc: "Morse code over copper wires. Information detaches from transport for the first time in history." },
  { id: "railroad-network", name: "Railroad Network", era: "industrial", category: "transport",
    year: "1840", prereqs: ["railway-locomotive", "telegraph"],
    desc: "Continental rail systems coordinated by telegraph. Standard time zones and national markets emerge." },
  { id: "steamship", name: "Steamship", era: "industrial", category: "transport",
    year: "1830", prereqs: ["steam-engine-watt", "naval-warship"],
    desc: "Iron-hulled screw-driven ocean steamers. Atlantic crossings drop from weeks to days, on schedule." },
  { id: "electric-battery", name: "Voltaic Battery", era: "industrial", category: "energy",
    year: "1800", prereqs: ["electricity-static", "chemistry-modern"],
    desc: "Volta's pile produces sustained current. Electricity becomes a tool, not a curiosity." },
  { id: "electromagnetism", name: "Electromagnetism", era: "industrial", category: "knowledge",
    year: "1820", prereqs: ["electric-battery", "calculus"],
    desc: "Ørsted, Faraday, Maxwell unify electricity and magnetism. Light is shown to be an electromagnetic wave." },
  { id: "electric-motor", name: "Electric Motor", era: "industrial", category: "energy",
    year: "1834", prereqs: ["electric-battery", "electromagnetism"],
    desc: "Rotary force from current in a magnetic field. Eventually replaces steam in factories and trams." },
  { id: "telephone", name: "Telephone", era: "industrial", category: "communication",
    year: "1876", prereqs: ["telegraph", "electromagnetism"],
    desc: "Bell's voice-over-wire patent. Real-time spoken communication across cities and then continents." },
  { id: "radio-wireless", name: "Radio", era: "industrial", category: "communication",
    year: "1895", prereqs: ["electromagnetism", "telegraph"],
    desc: "Marconi's wireless transmission. Communication without wires — first ships, then everyone." },
  { id: "photography", name: "Photography", era: "industrial", category: "communication",
    year: "1839", prereqs: ["chemistry-modern", "glass-lens"],
    desc: "Daguerreotype and calotype processes. Mechanical reproduction of visual reality." },
  { id: "cinema", name: "Cinema", era: "industrial", category: "communication",
    year: "1895", prereqs: ["photography"],
    desc: "Lumière brothers project moving images to a paying audience. A new mass medium is born." },
  { id: "oil-petroleum", name: "Oil Industry", era: "industrial", category: "energy",
    year: "1859", prereqs: ["chemistry-modern"],
    desc: "Drake well in Pennsylvania, then global drilling. A century of cheap, dense, transportable energy." },
  { id: "internal-combustion", name: "Internal Combustion Engine", era: "industrial", category: "energy",
    year: "1876", prereqs: ["steam-engine-watt", "chemistry-modern", "oil-petroleum"],
    desc: "Otto's four-stroke cycle. Power-to-weight ratios that steam can't match — the engine of cars and planes." },
  { id: "automobile", name: "Automobile", era: "industrial", category: "transport",
    year: "1886", prereqs: ["internal-combustion", "bessemer-steel"],
    desc: "Benz Patent-Motorwagen. Personal mechanized transport reshapes cities within 50 years." },
  { id: "bicycle", name: "Safety Bicycle", era: "industrial", category: "transport",
    year: "1885", prereqs: ["bessemer-steel", "gear-mechanism"],
    desc: "Equal-wheel chain-driven bicycle. Cheap personal mobility — and a precursor to automotive engineering." },
  { id: "evolution-darwin", name: "Theory of Evolution", era: "industrial", category: "knowledge",
    year: "1859", prereqs: ["scientific-method", "selective-breeding"],
    desc: "Darwin and Wallace propose descent with modification by natural selection. Biology gets its unifying theory." },
  { id: "germ-theory", name: "Germ Theory", era: "industrial", category: "medicine",
    year: "1860", prereqs: ["germ-precursor", "evolution-darwin"],
    desc: "Pasteur and Koch link specific microbes to specific diseases. Medicine gains a causal mechanism." },
  { id: "antiseptic-surgery", name: "Antiseptic Surgery", era: "industrial", category: "medicine",
    year: "1867", prereqs: ["germ-theory"],
    desc: "Lister's carbolic acid practices. Surgical mortality drops from majority to minority overnight." },
  { id: "anesthesia", name: "Anesthesia", era: "industrial", category: "medicine",
    year: "1846", prereqs: ["chemistry-modern", "anatomy-vesalius"],
    desc: "Ether and chloroform render patients insensate. Long, careful operations become possible." },
  { id: "public-sanitation", name: "Sanitation Engineering", era: "industrial", category: "medicine",
    year: "1858", prereqs: ["germ-theory", "aqueduct"],
    desc: "Sewers, water treatment, and urban hygiene laws. Cholera and typhoid retreat from cities." },
  { id: "vaccination-mass", name: "Mass Vaccination", era: "industrial", category: "medicine",
    year: "1880", prereqs: ["vaccination", "germ-theory"],
    desc: "Pasteur's attenuated rabies and anthrax vaccines extend Jenner's principle to many diseases." },
  { id: "thermodynamics", name: "Thermodynamics", era: "industrial", category: "knowledge",
    year: "1850", prereqs: ["steam-engine-watt", "calculus"],
    desc: "Carnot, Clausius, Kelvin formalize energy and entropy. The engine builders' empirical laws become physics." },
  { id: "periodic-table", name: "Periodic Table", era: "industrial", category: "knowledge",
    year: "1869", prereqs: ["chemistry-modern"],
    desc: "Mendeleev arranges elements by mass and predicts the gaps. Chemistry becomes a structured science." },
  { id: "atomic-theory", name: "Atomic Theory", era: "industrial", category: "knowledge",
    year: "1808", prereqs: ["chemistry-modern", "periodic-table"],
    desc: "Dalton's law of multiple proportions through Boltzmann's statistical mechanics. Atoms gain mass and reality." },
  { id: "electron-discovery", name: "Electron", era: "industrial", category: "knowledge",
    year: "1897", prereqs: ["atomic-theory", "electromagnetism"],
    desc: "J.J. Thomson identifies cathode rays as particles smaller than atoms. The atom has parts." },
  { id: "x-ray", name: "X-Ray", era: "industrial", category: "medicine",
    year: "1895", prereqs: ["electromagnetism", "atomic-theory"],
    desc: "Röntgen's photographs of bones inside living flesh. Diagnostic imaging is born within months." },
  { id: "machine-tool", name: "Machine Tools", era: "industrial", category: "tools",
    year: "1820", prereqs: ["bessemer-steel", "factory-system"],
    desc: "Lathes, mills, and shapers cutting metal to specification. Machines that make machines." },
  { id: "interchangeable-parts", name: "Interchangeable Parts", era: "industrial", category: "tools",
    year: "1820", prereqs: ["machine-tool", "factory-system"],
    desc: "Whitney and Hall produce muskets with swappable components. Mass repair, mass assembly." },
  { id: "assembly-line", name: "Assembly Line", era: "industrial", category: "economy",
    year: "1913", prereqs: ["interchangeable-parts", "factory-system"],
    desc: "Ford's moving line produces a Model T every 93 seconds. Cars become mass-market goods." },
  { id: "modern-corporation", name: "Modern Corporation", era: "industrial", category: "economy",
    year: "1880", prereqs: ["joint-stock-company", "factory-system"],
    desc: "Limited-liability hierarchical firms with professional management. Standard Oil, US Steel define the form." },
  { id: "labor-union", name: "Labor Union", era: "industrial", category: "economy",
    year: "1850", prereqs: ["factory-system", "liberal-democracy"],
    desc: "Organized collective bargaining. Industrial workers gain voice and the eventual eight-hour day." },
  { id: "newspaper-mass", name: "Mass Newspaper", era: "industrial", category: "communication",
    year: "1850", prereqs: ["printing-press", "telegraph"],
    desc: "Penny press and wire services. Daily news for everyone, funded by advertising." },
  { id: "skyscraper", name: "Skyscraper", era: "industrial", category: "shelter",
    year: "1885", prereqs: ["bessemer-steel", "electric-motor"],
    desc: "Steel-frame buildings beyond stone's height limit. Chicago and New York climb skyward." },
  { id: "elevator", name: "Safety Elevator", era: "industrial", category: "tools",
    year: "1857", prereqs: ["bessemer-steel", "electric-motor"],
    desc: "Otis's safety brake makes vertical buildings habitable. The skyscraper's necessary partner." },
  { id: "machine-gun", name: "Machine Gun", era: "industrial", category: "weapons",
    year: "1884", prereqs: ["artillery", "interchangeable-parts"],
    desc: "Maxim's recoil-operated automatic. Industrial-scale lethality that ends Napoleonic tactics." },
  { id: "electrification", name: "Grid Electrification", era: "industrial", category: "energy",
    year: "1882", prereqs: ["electric-motor", "electromagnetism"],
    desc: "Edison and Tesla's competing grids deliver electricity to homes and factories. Light, motors, and information on tap." },

  // ─── Modern ────────────────────────────────────────────────────
  { id: "airplane", name: "Airplane", era: "modern", category: "transport",
    year: "1903", prereqs: ["internal-combustion", "bicycle"],
    desc: "Wright Flyer at Kitty Hawk. Heavier-than-air controlled flight — within 50 years it crosses oceans daily." },
  { id: "relativity", name: "Relativity", era: "modern", category: "knowledge",
    year: "1905", prereqs: ["electromagnetism", "thermodynamics"],
    desc: "Einstein's special and general theories. Space, time, mass, and gravity revealed as a single geometry." },
  { id: "quantum-mechanics", name: "Quantum Mechanics", era: "modern", category: "knowledge",
    year: "1925", prereqs: ["atomic-theory", "relativity"],
    desc: "Heisenberg, Schrödinger, Dirac formulate matter at the atomic scale. The basis of nearly all modern technology." },
  { id: "radar", name: "Radar", era: "modern", category: "knowledge",
    year: "1935", prereqs: ["radio-wireless", "electromagnetism"],
    desc: "Radio echo-location of aircraft and ships. Wins the Battle of Britain and seeds microwave electronics." },
  { id: "helicopter", name: "Helicopter", era: "modern", category: "transport",
    year: "1939", prereqs: ["airplane"],
    desc: "Sikorsky's single-rotor design. Vertical takeoff and hover for rescue, medevac, and warfare." },
  { id: "jet-engine", name: "Jet Engine", era: "modern", category: "transport",
    year: "1939", prereqs: ["airplane", "thermodynamics"],
    desc: "Whittle and von Ohain's gas turbines. Doubles airliner speeds and altitudes by the 1960s." },
  { id: "rocket", name: "Liquid-Fuel Rocket", era: "modern", category: "transport",
    year: "1942", prereqs: ["jet-engine", "chemistry-modern"],
    desc: "V-2 reaches space, then the descendants take humans there. A launchable engine that carries its own oxidizer." },
  { id: "nuclear-fission", name: "Nuclear Fission", era: "modern", category: "energy",
    year: "1938", prereqs: ["quantum-mechanics", "electron-discovery"],
    desc: "Hahn and Meitner split uranium. A million-fold energy density compared to chemical fuels." },
  { id: "nuclear-weapon", name: "Nuclear Weapon", era: "modern", category: "weapons",
    year: "1945", prereqs: ["nuclear-fission"],
    desc: "Trinity, Hiroshima, Nagasaki. Strategy, sovereignty, and existential risk all change in a single year." },
  { id: "nuclear-power", name: "Nuclear Power", era: "modern", category: "energy",
    year: "1954", prereqs: ["nuclear-fission"],
    desc: "Civilian fission reactors generate electricity. Carbon-free baseload — and an unsolved waste problem." },
  { id: "antibiotics", name: "Antibiotics", era: "modern", category: "medicine",
    year: "1928", prereqs: ["germ-theory", "chemistry-modern"],
    desc: "Fleming's penicillin, then sulfa, streptomycin, tetracycline. Bacterial infection becomes mostly treatable." },
  { id: "vaccines-modern", name: "Modern Vaccines", era: "modern", category: "medicine",
    year: "1955", prereqs: ["vaccination-mass", "germ-theory"],
    desc: "Salk's polio vaccine and successors. Smallpox eradicated; polio nearly so." },
  { id: "dna-structure", name: "DNA Double Helix", era: "modern", category: "knowledge",
    year: "1953", prereqs: ["x-ray", "evolution-darwin"],
    desc: "Watson, Crick, Franklin, Wilkins reveal the molecule of inheritance. Biology becomes information science." },
  { id: "synthetic-fertilizer", name: "Haber–Bosch Process", era: "modern", category: "subsistence",
    year: "1913", prereqs: ["chemistry-modern", "agricultural-revolution"],
    desc: "Atmospheric nitrogen fixed into ammonia at industrial scale. Feeds roughly half of all humans alive." },
  { id: "green-revolution", name: "Green Revolution", era: "modern", category: "subsistence",
    year: "1960", prereqs: ["synthetic-fertilizer", "selective-breeding"],
    desc: "Borlaug's high-yield wheat, irrigation, and fertilizer packages. Famine recedes from much of Asia." },
  { id: "plastic-polymer", name: "Plastics", era: "modern", category: "tools",
    year: "1907", prereqs: ["chemistry-modern", "oil-petroleum"],
    desc: "Bakelite, then polyethylene and PVC. Cheap, moldable, durable — and persistent in the environment." },
  { id: "transistor", name: "Transistor", era: "modern", category: "tools",
    year: "1947", prereqs: ["quantum-mechanics", "electron-discovery"],
    desc: "Bell Labs' solid-state amplifier. Replaces the vacuum tube and shrinks electronics by orders of magnitude." },
  { id: "semiconductor", name: "Integrated Circuit", era: "modern", category: "tools",
    year: "1958", prereqs: ["transistor"],
    desc: "Kilby and Noyce etch many transistors on one silicon die. The road to Moore's Law begins." },
  { id: "digital-computer", name: "Digital Computer", era: "modern", category: "knowledge",
    year: "1945", prereqs: ["transistor", "machine-tool", "mathematics-arithmetic"],
    desc: "ENIAC, EDSAC, and the von Neumann architecture. Stored-program machines compute anything computable." },
  { id: "programming-language", name: "Programming Languages", era: "modern", category: "communication",
    year: "1957", prereqs: ["digital-computer"],
    desc: "FORTRAN, LISP, COBOL, ALGOL. Humans instruct machines in something more than raw bits." },
  { id: "mainframe", name: "Mainframe", era: "modern", category: "tools",
    year: "1964", prereqs: ["digital-computer", "semiconductor"],
    desc: "IBM System/360 unifies a family of machines. Business computing on a global scale." },
  { id: "television", name: "Television", era: "modern", category: "communication",
    year: "1928", prereqs: ["cinema", "radio-wireless"],
    desc: "Broadcast moving images into the home. A century-defining mass medium." },
  { id: "satellite", name: "Artificial Satellite", era: "modern", category: "communication",
    year: "1957", prereqs: ["rocket", "radio-wireless"],
    desc: "Sputnik, then Telstar. Communications, weather, navigation, and reconnaissance from orbit." },
  { id: "spaceflight", name: "Human Spaceflight", era: "modern", category: "transport",
    year: "1961", prereqs: ["rocket", "satellite"],
    desc: "Gagarin orbits the Earth. Humans become a spacefaring species." },
  { id: "moon-landing", name: "Moon Landing", era: "modern", category: "transport",
    year: "1969", prereqs: ["spaceflight", "digital-computer"],
    desc: "Apollo 11 walks on another world. The high-water mark of 20th-century crewed exploration." },
  { id: "mass-media", name: "Mass Media", era: "modern", category: "communication",
    year: "1950", prereqs: ["television", "newspaper-mass"],
    desc: "Radio, TV, magazines as a unified cultural pipeline. Shared narratives across nations." },
  { id: "consumer-economy", name: "Consumer Economy", era: "modern", category: "economy",
    year: "1950", prereqs: ["assembly-line", "mass-media"],
    desc: "Mass production meets mass advertising. Suburbs, cars, appliances, and credit-fueled abundance." },
  { id: "credit-card", name: "Credit Card", era: "modern", category: "economy",
    year: "1958", prereqs: ["modern-corporation", "telephone"],
    desc: "BankAmericard becomes Visa. Revolving consumer credit decoupled from any single merchant." },
  { id: "container-shipping", name: "Container Shipping", era: "modern", category: "transport",
    year: "1956", prereqs: ["steamship", "assembly-line"],
    desc: "McLean's standardized boxes. Intermodal freight costs collapse — globalization's logistical backbone." },
  { id: "highway-system", name: "Interstate Highway", era: "modern", category: "transport",
    year: "1956", prereqs: ["automobile", "internal-combustion"],
    desc: "Limited-access national road networks. Reshape settlement, retail, and freight patterns." },
  { id: "welfare-state", name: "Welfare State", era: "modern", category: "economy",
    year: "1945", prereqs: ["liberal-democracy", "public-education"],
    desc: "Social insurance, public healthcare, pensions. Postwar consensus across the rich democracies." },
  { id: "decolonization", name: "Decolonization", era: "modern", category: "economy",
    year: "1947", prereqs: ["nation-state", "world-religion"],
    desc: "European empires dissolve into dozens of independent states across Asia and Africa." },
  { id: "united-nations", name: "International Order", era: "modern", category: "economy",
    year: "1945", prereqs: ["liberal-democracy", "decolonization"],
    desc: "UN, IMF, GATT/WTO. Multilateral institutions managing trade, security, and human rights." },
  { id: "birth-control", name: "Hormonal Contraception", era: "modern", category: "medicine",
    year: "1960", prereqs: ["chemistry-modern", "vaccines-modern"],
    desc: "The Pill decouples sex from reproduction. Demographics and gender roles transform within a generation." },
  { id: "air-conditioning", name: "Air Conditioning", era: "modern", category: "tools",
    year: "1902", prereqs: ["electric-motor", "chemistry-modern"],
    desc: "Carrier's mechanical refrigeration. Makes the Sun Belt habitable and modern computing possible." },

  // ─── Information ───────────────────────────────────────────────
  { id: "microprocessor", name: "Microprocessor", era: "information", category: "tools",
    year: "1971", prereqs: ["transistor", "semiconductor"],
    desc: "Intel 4004 puts a CPU on a single chip. The foundation of every device that follows." },
  { id: "personal-computer", name: "Personal Computer", era: "information", category: "tools",
    year: "1977", prereqs: ["microprocessor", "mainframe"],
    desc: "Apple II, IBM PC, and the clone ecosystem. Computing escapes the data center for the desk." },
  { id: "gui-mouse", name: "Graphical Interface", era: "information", category: "communication",
    year: "1984", prereqs: ["personal-computer"],
    desc: "Xerox PARC's WIMP, popularized by Mac and Windows. Computers become usable without a manual." },
  { id: "packet-switching", name: "Packet Switching", era: "information", category: "communication",
    year: "1969", prereqs: ["digital-computer", "programming-language"],
    desc: "Baran and Kleinrock's design splits messages into routed packets. Resilient, shared, scalable networks." },
  { id: "arpanet-internet", name: "Internet", era: "information", category: "communication",
    year: "1983", prereqs: ["mainframe", "satellite", "packet-switching"],
    desc: "TCP/IP unites ARPANET and successors into a network of networks. The default global communications layer." },
  { id: "email", name: "Email", era: "information", category: "communication",
    year: "1971", prereqs: ["arpanet-internet"],
    desc: "Tomlinson's @-addressed mail. Asynchronous messaging that quietly replaced the memo and the letter." },
  { id: "world-wide-web", name: "World Wide Web", era: "information", category: "communication",
    year: "1991", prereqs: ["arpanet-internet", "gui-mouse"],
    desc: "Berners-Lee's HTTP, HTML, URLs. Hypertext over the internet — an open publishing platform for everyone." },
  { id: "search-engine", name: "Search Engine", era: "information", category: "communication",
    year: "1998", prereqs: ["world-wide-web", "digital-computer"],
    desc: "PageRank organizes the web by link structure. Finding becomes more important than browsing." },
  { id: "fiber-optic", name: "Fiber Optic Cable", era: "information", category: "communication",
    year: "1988", prereqs: ["semiconductor", "glass-lens"],
    desc: "Total internal reflection in glass strands. Trans-oceanic data at terabits per second." },
  { id: "mobile-phone", name: "Mobile Phone", era: "information", category: "communication",
    year: "1983", prereqs: ["telephone", "microprocessor"],
    desc: "Cellular networks plus pocket handsets. Telephony untethered from any wall." },
  { id: "smartphone", name: "Smartphone", era: "information", category: "communication",
    year: "2007", prereqs: ["mobile-phone", "world-wide-web", "gui-mouse"],
    desc: "iPhone and Android. A networked computer in everyone's pocket — the dominant computing form factor." },
  { id: "social-media", name: "Social Media", era: "information", category: "social",
    year: "2004", prereqs: ["world-wide-web", "smartphone"],
    desc: "Facebook, Twitter, YouTube, TikTok. Public discourse, advertising, and identity restructured around the feed." },
  { id: "streaming-media", name: "Streaming Media", era: "information", category: "communication",
    year: "2007", prereqs: ["world-wide-web", "semiconductor"],
    desc: "Netflix, YouTube, Spotify deliver media on demand. Broadcast and physical distribution collapse." },
  { id: "cloud-computing", name: "Cloud Computing", era: "information", category: "tools",
    year: "2006", prereqs: ["arpanet-internet", "mainframe"],
    desc: "AWS and successors rent compute by the second. Capital expense becomes operating expense; mainframes return as a service." },
  { id: "ecommerce", name: "E-Commerce", era: "information", category: "economy",
    year: "1995", prereqs: ["world-wide-web", "credit-card"],
    desc: "Amazon, eBay, Alibaba. Storefront-to-customer disintermediation at planetary scale." },
  { id: "gps", name: "GPS", era: "information", category: "transport",
    year: "1995", prereqs: ["satellite", "microprocessor"],
    desc: "24-satellite trilateration giving meter-scale civilian positioning. Maps fold into pockets." },
  { id: "gene-sequencing", name: "Genome Sequencing", era: "information", category: "medicine",
    year: "2003", prereqs: ["dna-structure", "digital-computer"],
    desc: "Human Genome Project, then exponential cost decline. Reading genomes goes from megaprojects to days." },
  { id: "genetic-engineering", name: "Recombinant DNA", era: "information", category: "medicine",
    year: "1973", prereqs: ["dna-structure"],
    desc: "Boyer and Cohen splice genes between organisms. Insulin, GM crops, and the biotech industry follow." },
  { id: "crispr", name: "CRISPR", era: "information", category: "medicine",
    year: "2012", prereqs: ["gene-sequencing", "genetic-engineering"],
    desc: "Doudna and Charpentier repurpose a bacterial immune system as a precision gene editor. Fast, cheap, programmable biology." },
  { id: "mri-imaging", name: "MRI Imaging", era: "information", category: "medicine",
    year: "1977", prereqs: ["x-ray", "digital-computer"],
    desc: "Magnetic resonance plus computation produces soft-tissue images without radiation. Diagnostic medicine transformed." },
  { id: "ivf", name: "In Vitro Fertilization", era: "information", category: "medicine",
    year: "1978", prereqs: ["birth-control", "gene-sequencing"],
    desc: "Edwards and Steptoe deliver Louise Brown. Reproduction joins medicine's deliberate domain." },
  { id: "mrna-vaccine", name: "mRNA Vaccine", era: "information", category: "medicine",
    year: "2020", prereqs: ["vaccines-modern", "gene-sequencing"],
    desc: "Lipid-encapsulated messenger RNA encoding antigens. From pathogen sequence to manufactured vaccine in weeks." },
  { id: "solar-photovoltaic", name: "Solar Photovoltaic", era: "information", category: "energy",
    year: "1980", prereqs: ["semiconductor", "electrification"],
    desc: "Silicon panels converting sunlight to electricity. Costs fall 100× over four decades." },
  { id: "wind-turbine", name: "Wind Turbine", era: "information", category: "energy",
    year: "1985", prereqs: ["windmill", "electric-motor"],
    desc: "Multi-megawatt utility-scale generators. Cheapest new electricity in many markets by the 2020s." },
  { id: "lithium-battery", name: "Lithium-Ion Battery", era: "information", category: "energy",
    year: "1991", prereqs: ["electric-battery", "semiconductor"],
    desc: "Goodenough's intercalation chemistry. The energy storage that makes laptops, phones, and EVs viable." },
  { id: "electric-vehicle", name: "Electric Vehicle", era: "information", category: "transport",
    year: "2008", prereqs: ["lithium-battery", "automobile"],
    desc: "Tesla Roadster and successors. EVs return to the road a century after losing to internal combustion." },
  { id: "renewable-grid", name: "Renewable Grid", era: "information", category: "energy",
    year: "2020", prereqs: ["solar-photovoltaic", "wind-turbine", "lithium-battery"],
    desc: "Variable renewables paired with storage. The first viable path to deep grid decarbonization." },
  { id: "machine-learning", name: "Machine Learning", era: "information", category: "knowledge",
    year: "1990", prereqs: ["digital-computer", "programming-language", "probability-theory"],
    desc: "Programs that improve from data. Statistics, optimization, and computation merge into a discipline." },
  { id: "deep-learning", name: "Deep Learning", era: "information", category: "knowledge",
    year: "2012", prereqs: ["machine-learning", "cloud-computing"],
    desc: "Neural networks at GPU scale (AlexNet). Vision, speech, translation, and games rapidly fall." },
  { id: "large-language-model", name: "Large Language Model", era: "information", category: "knowledge",
    year: "2020", prereqs: ["deep-learning", "world-wide-web"],
    desc: "Transformer-based models trained on internet text. General-purpose language and reasoning at human-comparable levels in many tasks." },
  { id: "cryptocurrency", name: "Cryptocurrency", era: "information", category: "economy",
    year: "2009", prereqs: ["world-wide-web", "central-bank"],
    desc: "Bitcoin and successors. Cryptographically scarce assets without an issuing institution — a contested experiment in money." },
  { id: "reusable-rocket", name: "Reusable Rocket", era: "information", category: "transport",
    year: "2015", prereqs: ["rocket", "machine-learning"],
    desc: "Falcon 9 lands and reflies first stages. Launch costs fall an order of magnitude — orbit becomes routine." },
  { id: "autonomous-vehicle", name: "Autonomous Vehicle", era: "information", category: "transport",
    year: "2020", prereqs: ["electric-vehicle", "machine-learning", "gps"],
    desc: "Self-driving cars and trucks moving from demos to commercial fleets in select cities." },
  { id: "3d-printing", name: "3D Printing", era: "information", category: "tools",
    year: "1990", prereqs: ["machine-tool", "digital-computer"],
    desc: "Additive layered manufacturing. From rapid prototyping to printed organs, rockets, and houses." },
  { id: "robotics", name: "Robotics", era: "information", category: "tools",
    year: "1980", prereqs: ["digital-computer", "machine-tool"],
    desc: "Industrial arms, then mobile and humanoid platforms. Programmable physical labor, increasingly with learned policies." },
  { id: "quantum-computing", name: "Quantum Computing", era: "information", category: "knowledge",
    year: "2019", prereqs: ["quantum-mechanics", "microprocessor"],
    desc: "Programmable qubits demonstrating supremacy on niche tasks. Cryptography and chemistry are the long-term targets." },
  { id: "climate-science", name: "Climate Science", era: "information", category: "knowledge",
    year: "1988", prereqs: ["scientific-method", "digital-computer", "satellite"],
    desc: "Coupled atmosphere-ocean models, satellite observation, and IPCC consensus. The global carbon budget becomes legible." },
];

window.TECH_TREE = { ERAS, CATEGORIES, TECHS };
