#!/usr/bin/env python3
"""Add 8 arts/entertainment techs (3 Near Future, 5 Far Future) to data.js,
translations.js, unlocks.js. Image fetching is in a separate script."""

import json
from pathlib import Path

ROOT = Path("/Users/haomingwang/Desktop/Python/tech-tree")
DATA = ROOT / "data.js"
TRANS = ROOT / "translations.js"
UNLOCKS_PATH = ROOT / "unlocks.js"

NEW_BLOCK = """
  // ─── Near Future / Far Future arts & entertainment ───
  { id: "synthetic-performers", name: "Synthetic Performers", era: "future", category: "social",
    year: "2035", prereqs: ["large-language-model", "generative-art"],
    desc: "AI-driven virtual idols and synthetic celebrities operating across music, film, and social media. Hatsune Miku (Crypton Future Media, 2007) — a Vocaloid character with sold-out arena holographic concerts — was the early prototype. Lil Miquela (2016) and Kizuna AI (2016) extended the form into Instagram-style influencers and VTubers. By the 2030s fully autonomous AI performers — generating their own music, dialogue, fan interactions, and tours — outdraw human acts in some markets. The economic dynamics flip: a synthetic performer never ages, never tires, and exists in unlimited parallel performances; the question of artistic authenticity gets reframed for the first time since recorded sound." },
  { id: "procedural-infinite-worlds", name: "Procedural Infinite Worlds", era: "future", category: "social",
    year: "2045", prereqs: ["video-games", "large-language-model"],
    desc: "Game and narrative environments generated on-demand from procedural rules and large language models — every player explores a different unique universe, dynamically generated as they walk through it. Dwarf Fortress (2006), Minecraft (2009), and No Man's Sky (2016) pioneered the approach with hand-crafted generators; AI-driven procgen by the 2040s produces fully novel storylines, characters, dialogue, and quests at runtime. The shift collapses content production economics — a single world can absorb millions of player-hours from a small studio's output — and fragments the shared cultural reference points that traditional games once produced." },
  { id: "bio-art", name: "Bio-Art", era: "future", category: "social",
    year: "2050", prereqs: ["synthetic-biology", "genetic-engineering"],
    desc: "Engineered living organisms — bacteria, plants, animals, tissue cultures — used as the artistic medium itself. Eduardo Kac's GFP Bunny (2000, transgenic green-fluorescent rabbit) and his microbial Genesis project (1999) opened the form. Stelarc's Ear on Arm (2007) extended it to performance art. SymbioticA (University of Western Australia, 2000–) became the institutional center. By 2050 maturity of CRISPR, synthetic biology, and biocontainment makes commissioned bio-art a recognized practice — installation pieces in galleries that grow, age, evolve, and require care. The boundary between art object and living system dissolves." },
  { id: "mind-linked-collective-art", name: "Mind-Linked Collective Art", era: "far-future", category: "social",
    year: "2200", prereqs: ["brain-computer-interface", "cybernetic-enhancement"],
    desc: "Direct multi-mind shared experience as artistic medium: hundreds to thousands of participants link via mature BCI mesh into a co-experienced subjective space, a single emergent qualia stream the artist composes for. Earlier precursors include collective dance, communal religious ritual, and large-scale immersive theater (Sleep No More 2011, Punchdrunk's heritage). Once neural interfaces enable real-time shared sensation and emotion, the artistic possibilities exceed anything previously available — the work exists not in any single mind but in the structured resonance across the linked group. Whether the resulting experience is one person's or many becomes a contested ontological question." },
  { id: "engineered-sensory-modalities", name: "Engineered Sensory Modalities", era: "far-future", category: "social",
    year: "2300", prereqs: ["cybernetic-enhancement", "nanotechnology"],
    desc: "Designed sensory channels purpose-built for art: magnetoreception, polarization vision, electric-field sensing, designed qualia bands with no biological precedent. Earlier work — Neil Harbisson's antennal hearing of color (2004), Moon Ribas's seismic sensor implant — explored the form within the constraints of a baseline human nervous system. Mature neuroengineering breaks those constraints; new senses are commissioned and installed for specific artworks, then optionally removed. The artistic vocabulary expands beyond what evolved-from-Earth nervous systems could carry, producing art forms that genuinely cannot be appreciated by unmodified humans." },
  { id: "ai-native-art-forms", name: "AI-Native Art Forms", era: "far-future", category: "social",
    year: "2400", prereqs: ["superintelligence", "matrioshka-brain"],
    desc: "Artworks generated by superintelligent systems for superintelligent audiences, operating at structural complexity and temporal compression beyond human cognitive bandwidth. Whereas earlier AI art (DALL-E 2022, Sora 2024, generative-art descendants) was produced by AI for human appreciation, AI-native art forms are produced by AI for AI — and are largely opaque or trivial to baseline humans. The most accessible categories admit guided human interpretation; the rest exist in subjective spaces no embodied biological mind can occupy. Whether such works carry meaning, beauty, or value in any sense humans recognize becomes a recurring question for posthuman aesthetics." },
  { id: "stellar-scale-spectacle", name: "Stellar-Scale Spectacle", era: "far-future", category: "social",
    year: "2450", prereqs: ["dyson-swarm", "kardashev-type-ii"],
    desc: "Engineered modulation of stellar light output — controlled brightness pulses, color shifts, and engineered occlusion patterns visible across light-years — used as a cosmic-scale artistic medium. The Shkadov thruster (Leonid Shkadov, 1987) demonstrates the engineering basis; coordinated Dyson-swarm shutters provide a finer instrument. A Type II civilization can compose works in stellar pixels visible across the galaxy, with rendering times measured in centuries and audiences spread across thousands of star systems. The first stellar-scale spectacle is also a SETI signature — distinguishable from natural variable-star phenomena by its information content." },
  { id: "pan-galactic-festival", name: "Pan-Galactic Festival", era: "far-future", category: "social",
    year: "2600", prereqs: ["galactic-civilization", "galactic-communication-network"],
    desc: "Synchronized cultural events spanning the colonized galaxy, organized around shared themes despite light-lag latencies measured in millennia. The 'simultaneity' is virtual — each star system experiences its local festival in lockstep with thousands of others, despite none of them being in causal contact during the celebration itself. Cultural festivals (Olympics, Burning Man, Ramadan, Lunar New Year) are the small precursors; the pan-galactic festival operates at a scale where the act of *imagining* a galaxy-wide cultural moment is itself the meaningful event. Light-lag romanticism — the recognition that one's celebration coincides with celebrations one will never witness — becomes a defining aesthetic of galactic civilization." },
"""

TRANSLATIONS = {
    "synthetic-performers":          "合成表演者",
    "procedural-infinite-worlds":    "程序生成无限世界",
    "bio-art":                       "生物艺术",
    "mind-linked-collective-art":    "心智互联集体艺术",
    "engineered-sensory-modalities": "工程感官模态",
    "ai-native-art-forms":           "AI 原生艺术形式",
    "stellar-scale-spectacle":       "恒星尺度奇观",
    "pan-galactic-festival":         "泛银河庆典",
}

# (type, name, name_zh, wiki | False)
UNLOCKS = {
    "synthetic-performers": [
        ("unit",     "Hatsune Miku",         "初音未来",         "Hatsune Miku"),
        ("unit",     "Lil Miquela",          "Lil Miquela",      "Lil Miquela"),
        ("unit",     "Kizuna AI",            "绊爱",             "Kizuna AI"),
        ("resource", "Vocaloid",             "VOCALOID",         "Vocaloid"),
        ("org",      "Crypton Future Media", "克里普敦未来媒体", "Crypton Future Media"),
    ],
    "procedural-infinite-worlds": [
        ("work",     "No Man's Sky",         "《无人深空》",     "No Man's Sky"),
        ("work",     "Minecraft",            "《我的世界》",     "Minecraft"),
        ("work",     "Dwarf Fortress",       "《矮人要塞》",     "Dwarf Fortress"),
        ("resource", "Procedural generation","程序化生成",       "Procedural generation"),
    ],
    "bio-art": [
        ("person",   "Eduardo Kac",          "爱德华多·卡茨",   "Eduardo Kac"),
        ("work",     "GFP Bunny",            "《GFP 兔子》",     "GFP Bunny"),
        ("person",   "Stelarc",              "斯特拉克",         "Stelarc"),
        ("org",      "SymbioticA",           "SymbioticA 实验室","SymbioticA"),
        ("resource", "Transgenic art",       "转基因艺术",       "Transgenic art"),
    ],
    "mind-linked-collective-art": [
        ("resource", "Hive mind",            "蜂巢思维",         "Hive mind"),
        ("resource", "Telepathy",            "心灵感应",         "Telepathy"),
        ("work",     "Sleep No More",        "《不眠之夜》",     "Sleep No More (2011 play)"),
        ("unit",     "Collective-consciousness installation", "集体意识装置", False),
    ],
    "engineered-sensory-modalities": [
        ("resource", "Synesthesia",          "联觉",             "Synesthesia"),
        ("resource", "Sensory substitution", "感官替代",         "Sensory substitution"),
        ("person",   "Neil Harbisson",       "尼尔·哈维森",     "Neil Harbisson"),
        ("unit",     "Magnetoreception implant", "磁感受器植入", False),
    ],
    "ai-native-art-forms": [
        ("resource", "AI art",               "AI 艺术",          "AI art"),
        ("resource", "Generative art",       "生成艺术",         "Generative art"),
        ("unit",     "Substrate-specific composition", "基质特定作品", False),
        ("work",     "AI-incomprehensible artwork", "AI 不可理解作品", False),
    ],
    "stellar-scale-spectacle": [
        ("resource", "Shkadov thruster",     "什卡多夫推进器",   "Shkadov thruster"),
        ("resource", "Variable star",        "变星",             "Variable star"),
        ("unit",     "Modulated supergiant performance", "调制超巨星表演", False),
        ("wonder",   "Galactic light-show installation", "银河光秀装置", False),
    ],
    "pan-galactic-festival": [
        ("resource", "Cultural festival",    "文化节",           "Festival"),
        ("unit",     "Synchronized civilization rite", "同步文明仪式", False),
        ("work",     "Galactic Anthem",      "《银河颂歌》",     False),
        ("wonder",   "Pan-Galactic Coordination Ceremony", "泛银河协调典礼", False),
    ],
}


def splice_data():
    src = DATA.read_text()
    if "synthetic-performers" in src:
        print("data.js: already inserted"); return
    marker = "\n];\n\nwindow.TECH_TREE = { ERAS, CATEGORIES, TECHS };"
    if marker not in src:
        raise SystemExit("Closing marker not found")
    DATA.write_text(src.replace(marker, "\n" + NEW_BLOCK + "];\n\nwindow.TECH_TREE = { ERAS, CATEGORIES, TECHS };"))
    print(f"data.js: +{len(TRANSLATIONS)} arts techs")


def splice_translations():
    src = TRANS.read_text()
    if '"synthetic-performers"' in src:
        print("translations.js: already inserted"); return
    block = "\n  // ─── Near Future / Far Future arts & entertainment ───\n"
    for tid, zh in TRANSLATIONS.items():
        block += f'  "{tid}": "{zh}",\n'
    rs = src.rstrip(); assert rs.endswith("};")
    TRANS.write_text(rs[:-2] + block + "};\n")
    print(f"translations.js: +{len(TRANSLATIONS)}")


def splice_unlocks():
    src = UNLOCKS_PATH.read_text()
    if '"synthetic-performers"' in src:
        print("unlocks.js: already inserted"); return
    block = "\n  // ─── Near Future / Far Future arts & entertainment ───\n"
    for tid, items in UNLOCKS.items():
        block += f'  "{tid}": [\n'
        for typ, name, name_zh, wiki in items:
            wiki_part = ' wiki: false' if wiki is False else f' wiki: {json.dumps(wiki, ensure_ascii=False)}'
            block += (f'    {{ type: "{typ}", '
                      f'name: {json.dumps(name, ensure_ascii=False)}, '
                      f'name_zh: {json.dumps(name_zh, ensure_ascii=False)},'
                      f'{wiki_part} }},\n')
        block += '  ],\n'
    rs = src.rstrip(); assert rs.endswith("};")
    UNLOCKS_PATH.write_text(rs[:-2] + block + "};\n")
    print(f"unlocks.js: +{len(UNLOCKS)}")


if __name__ == "__main__":
    splice_data()
    splice_translations()
    splice_unlocks()
